# -*- coding: utf-8 -*-
"""
Bộ từ HSK 2 / HSK 3 / HSK 4 (chuẩn HSK cũ — phổ biến nhất hiện nay).
Format: (hanzi, pinyin, meaning_vn, example_zh, example_vn)
"""

# ============================================================
# HSK 2 — 150 từ (bao gồm các từ HSK 1 cốt lõi)
# ============================================================
HSK2 = [
    # Đại từ & xưng hô
    ("我", "wǒ", "tôi", "我是学生。", "Tôi là học sinh."),
    ("你", "nǐ", "bạn", "你好吗？", "Bạn khỏe không?"),
    ("他", "tā", "anh ấy", "他是医生。", "Anh ấy là bác sĩ."),
    ("她", "tā", "cô ấy", "她很漂亮。", "Cô ấy rất xinh."),
    ("我们", "wǒmen", "chúng tôi", "我们是朋友。", "Chúng tôi là bạn."),
    ("你们", "nǐmen", "các bạn", "你们好！", "Chào các bạn!"),
    ("他们", "tāmen", "họ", "他们在学习。", "Họ đang học."),
    ("它", "tā", "nó (đồ vật/con vật)", "它是我的猫。", "Nó là con mèo của tôi."),
    ("这", "zhè", "này, đây", "这是书。", "Đây là sách."),
    ("那", "nà", "kia, đó", "那是什么？", "Kia là cái gì?"),
    ("谁", "shéi", "ai", "他是谁？", "Anh ấy là ai?"),
    ("什么", "shénme", "cái gì", "你叫什么名字？", "Bạn tên gì?"),
    ("哪", "nǎ", "nào", "哪个是你的？", "Cái nào là của bạn?"),
    ("哪儿", "nǎr", "ở đâu", "你去哪儿？", "Bạn đi đâu?"),
    ("怎么", "zěnme", "thế nào", "怎么去车站？", "Đi đến ga thế nào?"),
    ("怎么样", "zěnmeyàng", "như thế nào", "今天怎么样？", "Hôm nay thế nào?"),
    ("为什么", "wèishénme", "tại sao", "你为什么不来？", "Tại sao bạn không đến?"),

    # Số đếm & đo lường
    ("一", "yī", "một", "我有一个哥哥。", "Tôi có một anh trai."),
    ("二", "èr", "hai", "二月很冷。", "Tháng hai rất lạnh."),
    ("三", "sān", "ba", "我有三本书。", "Tôi có ba quyển sách."),
    ("四", "sì", "bốn", "四点见面。", "Bốn giờ gặp nhau."),
    ("五", "wǔ", "năm", "五个苹果。", "Năm quả táo."),
    ("六", "liù", "sáu", "六月毕业。", "Tháng sáu tốt nghiệp."),
    ("七", "qī", "bảy", "七天一周。", "Bảy ngày một tuần."),
    ("八", "bā", "tám", "八点上班。", "Tám giờ đi làm."),
    ("九", "jiǔ", "chín", "九岁了。", "Chín tuổi rồi."),
    ("十", "shí", "mười", "十块钱。", "Mười tệ."),
    ("百", "bǎi", "trăm", "一百块。", "Một trăm tệ."),
    ("千", "qiān", "nghìn", "一千个人。", "Một nghìn người."),
    ("零", "líng", "không (số 0)", "零下五度。", "Âm năm độ."),
    ("两", "liǎng", "hai (số lượng)", "两个人。", "Hai người."),
    ("第一", "dì-yī", "thứ nhất", "我是第一名。", "Tôi đứng thứ nhất."),
    ("个", "gè", "cái (lượng từ)", "一个苹果。", "Một quả táo."),
    ("些", "xiē", "một vài", "买一些水果。", "Mua một ít trái cây."),
    ("多少", "duōshǎo", "bao nhiêu", "多少钱？", "Bao nhiêu tiền?"),
    ("几", "jǐ", "mấy", "几点了？", "Mấy giờ rồi?"),
    ("半", "bàn", "nửa", "一个半小时。", "Một tiếng rưỡi."),

    # Thời gian
    ("今天", "jīntiān", "hôm nay", "今天星期一。", "Hôm nay là thứ hai."),
    ("明天", "míngtiān", "ngày mai", "明天见。", "Hẹn gặp ngày mai."),
    ("昨天", "zuótiān", "hôm qua", "昨天下雨了。", "Hôm qua trời mưa."),
    ("现在", "xiànzài", "bây giờ", "现在几点？", "Bây giờ mấy giờ?"),
    ("早上", "zǎoshang", "buổi sáng", "早上好！", "Chào buổi sáng!"),
    ("中午", "zhōngwǔ", "buổi trưa", "中午吃饭。", "Trưa ăn cơm."),
    ("下午", "xiàwǔ", "buổi chiều", "下午有课。", "Chiều có giờ học."),
    ("晚上", "wǎnshang", "buổi tối", "晚上看电视。", "Tối xem tivi."),
    ("年", "nián", "năm", "今年我二十岁。", "Năm nay tôi 20 tuổi."),
    ("月", "yuè", "tháng", "三月开学。", "Tháng ba khai giảng."),
    ("日", "rì", "ngày", "五月一日。", "Ngày 1 tháng 5."),
    ("号", "hào", "ngày, số", "今天几号？", "Hôm nay ngày mấy?"),
    ("星期", "xīngqī", "tuần", "星期天休息。", "Chủ nhật nghỉ."),
    ("点", "diǎn", "giờ (chỉ giờ)", "三点见面。", "Ba giờ gặp."),
    ("分钟", "fēnzhōng", "phút", "等十分钟。", "Đợi mười phút."),
    ("小时", "xiǎoshí", "tiếng đồng hồ", "睡八个小时。", "Ngủ tám tiếng."),
    ("时候", "shíhou", "lúc, khi", "什么时候来？", "Khi nào đến?"),
    ("时间", "shíjiān", "thời gian", "我没有时间。", "Tôi không có thời gian."),
    ("以前", "yǐqián", "trước đây", "以前我住北京。", "Trước đây tôi sống ở Bắc Kinh."),

    # Gia đình & người
    ("爸爸", "bàba", "bố", "爸爸在工作。", "Bố đang làm việc."),
    ("妈妈", "māma", "mẹ", "妈妈做饭。", "Mẹ nấu cơm."),
    ("哥哥", "gēge", "anh trai", "哥哥是医生。", "Anh trai là bác sĩ."),
    ("姐姐", "jiějie", "chị gái", "姐姐结婚了。", "Chị gái kết hôn rồi."),
    ("弟弟", "dìdi", "em trai", "弟弟很可爱。", "Em trai rất dễ thương."),
    ("妹妹", "mèimei", "em gái", "妹妹上小学。", "Em gái học tiểu học."),
    ("儿子", "érzi", "con trai", "我的儿子五岁。", "Con trai tôi 5 tuổi."),
    ("女儿", "nǚ'ér", "con gái", "她有一个女儿。", "Cô ấy có một con gái."),
    ("丈夫", "zhàngfu", "chồng", "她的丈夫是老师。", "Chồng cô ấy là giáo viên."),
    ("妻子", "qīzi", "vợ", "我的妻子很漂亮。", "Vợ tôi rất xinh."),
    ("孩子", "háizi", "trẻ con", "孩子在玩。", "Trẻ con đang chơi."),
    ("男人", "nánrén", "đàn ông", "那个男人是谁？", "Người đàn ông kia là ai?"),
    ("女人", "nǚrén", "phụ nữ", "她是个好女人。", "Cô ấy là phụ nữ tốt."),
    ("朋友", "péngyou", "bạn bè", "他是我的朋友。", "Anh ấy là bạn tôi."),
    ("同学", "tóngxué", "bạn học", "他是我的同学。", "Anh ấy là bạn học của tôi."),
    ("老师", "lǎoshī", "giáo viên", "老师很严格。", "Giáo viên rất nghiêm."),
    ("学生", "xuésheng", "học sinh", "我是学生。", "Tôi là học sinh."),
    ("医生", "yīshēng", "bác sĩ", "他是医生。", "Anh ấy là bác sĩ."),
    ("先生", "xiānsheng", "ông, ngài", "王先生你好。", "Chào ông Vương."),
    ("小姐", "xiǎojiě", "cô (xưng hô)", "李小姐很漂亮。", "Cô Lý rất xinh."),

    # Động từ thông dụng
    ("是", "shì", "là", "我是越南人。", "Tôi là người Việt Nam."),
    ("有", "yǒu", "có", "我有一只猫。", "Tôi có một con mèo."),
    ("没", "méi", "không có", "我没有钱。", "Tôi không có tiền."),
    ("不", "bù", "không", "我不去。", "Tôi không đi."),
    ("去", "qù", "đi", "我去学校。", "Tôi đi học."),
    ("来", "lái", "đến", "他来了。", "Anh ấy đến rồi."),
    ("吃", "chī", "ăn", "我吃米饭。", "Tôi ăn cơm."),
    ("喝", "hē", "uống", "我喝水。", "Tôi uống nước."),
    ("看", "kàn", "xem, nhìn", "看电视。", "Xem tivi."),
    ("听", "tīng", "nghe", "听音乐。", "Nghe nhạc."),
    ("说", "shuō", "nói", "他说汉语。", "Anh ấy nói tiếng Trung."),
    ("读", "dú", "đọc", "读书。", "Đọc sách."),
    ("写", "xiě", "viết", "写字。", "Viết chữ."),
    ("学习", "xuéxí", "học tập", "我学习汉语。", "Tôi học tiếng Trung."),
    ("工作", "gōngzuò", "làm việc", "我在工作。", "Tôi đang làm việc."),
    ("做", "zuò", "làm", "做作业。", "Làm bài tập."),
    ("买", "mǎi", "mua", "买衣服。", "Mua quần áo."),
    ("卖", "mài", "bán", "卖水果。", "Bán trái cây."),
    ("睡觉", "shuìjiào", "đi ngủ", "我要睡觉了。", "Tôi đi ngủ đây."),
    ("起床", "qǐchuáng", "ngủ dậy", "我七点起床。", "Tôi dậy lúc 7 giờ."),
    ("走", "zǒu", "đi bộ", "走路上班。", "Đi bộ đi làm."),
    ("跑", "pǎo", "chạy", "我每天跑步。", "Tôi chạy bộ mỗi ngày."),
    ("回", "huí", "về", "我回家。", "Tôi về nhà."),
    ("到", "dào", "đến", "到了。", "Đến rồi."),
    ("住", "zhù", "sống, ở", "我住北京。", "Tôi sống ở Bắc Kinh."),
    ("坐", "zuò", "ngồi", "请坐。", "Xin mời ngồi."),
    ("站", "zhàn", "đứng", "站起来。", "Đứng dậy."),
    ("开", "kāi", "mở; lái", "开门。", "Mở cửa."),
    ("关", "guān", "đóng", "关窗户。", "Đóng cửa sổ."),
    ("给", "gěi", "cho", "给我一杯水。", "Cho tôi một cốc nước."),
    ("找", "zhǎo", "tìm", "我找钱包。", "Tôi tìm ví."),
    ("帮助", "bāngzhù", "giúp đỡ", "谢谢你的帮助。", "Cảm ơn sự giúp đỡ của bạn."),
    ("告诉", "gàosu", "nói cho biết", "告诉我答案。", "Nói cho tôi câu trả lời."),
    ("等", "děng", "đợi", "等一下。", "Đợi một chút."),
    ("问", "wèn", "hỏi", "我问老师。", "Tôi hỏi giáo viên."),
    ("回答", "huídá", "trả lời", "请回答问题。", "Xin trả lời câu hỏi."),
    ("认识", "rènshi", "quen biết", "很高兴认识你。", "Rất vui được quen bạn."),
    ("知道", "zhīdào", "biết", "我不知道。", "Tôi không biết."),
    ("觉得", "juéde", "cảm thấy", "我觉得很好。", "Tôi cảm thấy rất tốt."),
    ("想", "xiǎng", "muốn, nghĩ", "我想喝水。", "Tôi muốn uống nước."),
    ("要", "yào", "muốn, cần", "我要这个。", "Tôi muốn cái này."),
    ("能", "néng", "có thể", "我能帮你。", "Tôi có thể giúp bạn."),
    ("会", "huì", "biết (kỹ năng)", "我会说汉语。", "Tôi biết nói tiếng Trung."),
    ("可以", "kěyǐ", "có thể", "可以进来吗？", "Có thể vào không?"),
    ("喜欢", "xǐhuan", "thích", "我喜欢你。", "Tôi thích bạn."),
    ("爱", "ài", "yêu", "我爱我的家。", "Tôi yêu gia đình mình."),
    ("玩", "wán", "chơi", "孩子在玩。", "Trẻ đang chơi."),
    ("打", "dǎ", "đánh, chơi (bóng)", "打篮球。", "Chơi bóng rổ."),
    ("打电话", "dǎ diànhuà", "gọi điện thoại", "我打电话给你。", "Tôi gọi điện cho bạn."),
    ("游泳", "yóuyǒng", "bơi", "夏天游泳。", "Mùa hè đi bơi."),
    ("跳舞", "tiàowǔ", "nhảy múa", "她喜欢跳舞。", "Cô ấy thích nhảy múa."),
    ("唱歌", "chànggē", "hát", "唱歌很好听。", "Hát hay lắm."),
    ("旅游", "lǚyóu", "du lịch", "去中国旅游。", "Đi du lịch Trung Quốc."),
    ("送", "sòng", "tặng, đưa", "送礼物。", "Tặng quà."),
    ("出", "chū", "ra", "出门。", "Ra khỏi nhà."),
    ("进", "jìn", "vào", "请进。", "Mời vào."),
    ("穿", "chuān", "mặc", "穿衣服。", "Mặc quần áo."),
    ("洗", "xǐ", "rửa, giặt", "洗手。", "Rửa tay."),

    # Tính từ
    ("好", "hǎo", "tốt", "你好！", "Chào bạn!"),
    ("大", "dà", "to, lớn", "房子很大。", "Nhà rất to."),
    ("小", "xiǎo", "nhỏ", "小狗很可爱。", "Chó nhỏ rất dễ thương."),
    ("多", "duō", "nhiều", "很多人。", "Rất nhiều người."),
    ("少", "shǎo", "ít", "钱很少。", "Tiền rất ít."),
    ("热", "rè", "nóng", "今天很热。", "Hôm nay rất nóng."),
    ("冷", "lěng", "lạnh", "冬天很冷。", "Mùa đông rất lạnh."),
    ("新", "xīn", "mới", "新衣服。", "Quần áo mới."),
    ("旧", "jiù", "cũ", "旧书。", "Sách cũ."),
    ("高", "gāo", "cao", "他个子很高。", "Anh ấy cao."),
    ("长", "cháng", "dài", "头发很长。", "Tóc rất dài."),
    ("贵", "guì", "đắt", "太贵了。", "Đắt quá."),
    ("便宜", "piányi", "rẻ", "很便宜。", "Rất rẻ."),
    ("快", "kuài", "nhanh", "他跑得快。", "Anh ấy chạy nhanh."),
    ("慢", "màn", "chậm", "走得慢。", "Đi chậm."),
    ("远", "yuǎn", "xa", "学校很远。", "Trường rất xa."),
    ("近", "jìn", "gần", "家很近。", "Nhà rất gần."),
    ("早", "zǎo", "sớm", "早上好。", "Chào buổi sáng."),
    ("晚", "wǎn", "muộn", "我来晚了。", "Tôi đến muộn."),
    ("漂亮", "piàoliang", "đẹp", "她很漂亮。", "Cô ấy rất đẹp."),
    ("好吃", "hǎochī", "ngon", "这菜好吃。", "Món này ngon."),
    ("忙", "máng", "bận", "我很忙。", "Tôi rất bận."),
    ("累", "lèi", "mệt", "今天很累。", "Hôm nay rất mệt."),
    ("高兴", "gāoxìng", "vui", "我很高兴。", "Tôi rất vui."),
    ("快乐", "kuàilè", "vui vẻ", "生日快乐！", "Sinh nhật vui vẻ!"),
    ("对", "duì", "đúng", "你说得对。", "Bạn nói đúng."),
    ("错", "cuò", "sai", "我错了。", "Tôi sai rồi."),
    ("白", "bái", "trắng", "白色衣服。", "Áo trắng."),
    ("黑", "hēi", "đen", "黑头发。", "Tóc đen."),
    ("红", "hóng", "đỏ", "红玫瑰。", "Hoa hồng đỏ."),

    # Đồ vật & nơi chốn
    ("家", "jiā", "nhà", "我回家。", "Tôi về nhà."),
    ("学校", "xuéxiào", "trường học", "学校很大。", "Trường rất to."),
    ("饭店", "fàndiàn", "khách sạn / nhà hàng", "住饭店。", "Ở khách sạn."),
    ("商店", "shāngdiàn", "cửa hàng", "去商店。", "Đi cửa hàng."),
    ("医院", "yīyuàn", "bệnh viện", "他在医院。", "Anh ấy ở bệnh viện."),
    ("公司", "gōngsī", "công ty", "公司在上海。", "Công ty ở Thượng Hải."),
    ("机场", "jīchǎng", "sân bay", "去机场。", "Đến sân bay."),
    ("教室", "jiàoshì", "phòng học", "教室很安静。", "Phòng học yên tĩnh."),
    ("房间", "fángjiān", "phòng", "房间很干净。", "Phòng sạch sẽ."),
    ("书", "shū", "sách", "看书。", "Đọc sách."),
    ("桌子", "zhuōzi", "cái bàn", "桌子上有书。", "Trên bàn có sách."),
    ("椅子", "yǐzi", "cái ghế", "坐在椅子上。", "Ngồi trên ghế."),
    ("电脑", "diànnǎo", "máy tính", "用电脑工作。", "Dùng máy tính làm việc."),
    ("电视", "diànshì", "tivi", "看电视。", "Xem tivi."),
    ("电话", "diànhuà", "điện thoại", "电话响了。", "Điện thoại reo."),
    ("手机", "shǒujī", "điện thoại di động", "我的手机。", "Điện thoại của tôi."),
    ("汽车", "qìchē", "ô tô", "买汽车。", "Mua ô tô."),
    ("出租车", "chūzūchē", "taxi", "坐出租车。", "Đi taxi."),
    ("飞机", "fēijī", "máy bay", "坐飞机去。", "Đi bằng máy bay."),
    ("火车站", "huǒchēzhàn", "ga tàu hỏa", "去火车站。", "Đến ga."),
    ("公共汽车", "gōnggòng qìchē", "xe buýt", "坐公共汽车。", "Đi xe buýt."),
    ("路", "lù", "đường", "这条路很长。", "Con đường này dài."),
    ("门", "mén", "cửa", "开门。", "Mở cửa."),
    ("钱", "qián", "tiền", "我有钱。", "Tôi có tiền."),

    # Thức ăn
    ("米饭", "mǐfàn", "cơm", "吃米饭。", "Ăn cơm."),
    ("面条", "miàntiáo", "mì sợi", "吃面条。", "Ăn mì."),
    ("水", "shuǐ", "nước", "喝水。", "Uống nước."),
    ("茶", "chá", "trà", "喝茶。", "Uống trà."),
    ("咖啡", "kāfēi", "cà phê", "我喜欢咖啡。", "Tôi thích cà phê."),
    ("牛奶", "niúnǎi", "sữa bò", "喝牛奶。", "Uống sữa."),
    ("水果", "shuǐguǒ", "trái cây", "买水果。", "Mua trái cây."),
    ("苹果", "píngguǒ", "táo", "吃苹果。", "Ăn táo."),
    ("西瓜", "xīguā", "dưa hấu", "夏天吃西瓜。", "Mùa hè ăn dưa hấu."),
    ("鸡蛋", "jīdàn", "trứng gà", "吃鸡蛋。", "Ăn trứng."),
    ("鱼", "yú", "cá", "鱼很新鲜。", "Cá rất tươi."),
    ("羊肉", "yángròu", "thịt cừu", "羊肉很贵。", "Thịt cừu đắt."),

    # Thời tiết, thiên nhiên & khác
    ("天气", "tiānqì", "thời tiết", "天气很好。", "Thời tiết đẹp."),
    ("下雨", "xiàyǔ", "trời mưa", "今天下雨。", "Hôm nay trời mưa."),
    ("下雪", "xiàxuě", "trời tuyết", "北京下雪了。", "Bắc Kinh có tuyết."),
    ("晴", "qíng", "trời nắng", "今天晴天。", "Hôm nay trời nắng."),
    ("阴", "yīn", "trời âm u", "今天阴天。", "Hôm nay trời âm u."),
    ("猫", "māo", "con mèo", "我的猫很可爱。", "Mèo của tôi dễ thương."),
    ("狗", "gǒu", "con chó", "狗在叫。", "Chó đang sủa."),

    # Câu chào & giao tiếp cơ bản
    ("你好", "nǐ hǎo", "xin chào", "你好，我叫小明。", "Xin chào, tôi tên Tiểu Minh."),
    ("再见", "zàijiàn", "tạm biệt", "明天见，再见！", "Hẹn gặp ngày mai, tạm biệt!"),
    ("谢谢", "xièxie", "cảm ơn", "谢谢你！", "Cảm ơn bạn!"),
    ("不客气", "bú kèqi", "không có gì", "谢谢！不客气。", "Cảm ơn! Không có chi."),
    ("对不起", "duìbuqǐ", "xin lỗi", "对不起，我迟到了。", "Xin lỗi, tôi đến muộn."),
    ("没关系", "méi guānxi", "không sao", "没关系。", "Không sao đâu."),
    ("请", "qǐng", "xin, mời", "请坐。", "Xin mời ngồi."),
    ("名字", "míngzi", "tên", "你叫什么名字？", "Bạn tên gì?"),
    ("叫", "jiào", "tên là, gọi", "我叫小红。", "Tôi tên Tiểu Hồng."),
    ("岁", "suì", "tuổi", "我二十岁。", "Tôi 20 tuổi."),

    # Phương vị & giới từ
    ("在", "zài", "ở, đang", "我在家。", "Tôi đang ở nhà."),
    ("上", "shàng", "trên", "桌子上。", "Trên bàn."),
    ("下", "xià", "dưới", "床下。", "Dưới giường."),
    ("里", "lǐ", "trong", "房间里。", "Trong phòng."),
    ("外", "wài", "ngoài", "门外。", "Ngoài cửa."),
    ("前面", "qiánmiàn", "phía trước", "学校前面。", "Trước trường học."),
    ("后面", "hòumiàn", "phía sau", "我家后面。", "Sau nhà tôi."),
    ("左边", "zuǒbian", "bên trái", "在左边。", "Ở bên trái."),
    ("右边", "yòubian", "bên phải", "在右边。", "Ở bên phải."),
    ("旁边", "pángbiān", "bên cạnh", "她旁边。", "Bên cạnh cô ấy."),
    ("中间", "zhōngjiān", "ở giữa", "在中间。", "Ở giữa."),
    ("和", "hé", "và, với", "我和你。", "Tôi và bạn."),
    ("跟", "gēn", "với, theo", "跟我来。", "Theo tôi."),

    # Trạng từ & liên từ thường gặp
    ("很", "hěn", "rất", "很好。", "Rất tốt."),
    ("太", "tài", "quá", "太贵了。", "Đắt quá."),
    ("非常", "fēicháng", "vô cùng", "非常好。", "Vô cùng tốt."),
    ("都", "dōu", "đều", "我们都去。", "Chúng tôi đều đi."),
    ("也", "yě", "cũng", "我也去。", "Tôi cũng đi."),
    ("还", "hái", "còn, vẫn", "我还在学。", "Tôi vẫn đang học."),
    ("就", "jiù", "ngay, liền", "我马上就来。", "Tôi đến ngay."),
    ("已经", "yǐjīng", "đã", "已经吃了。", "Đã ăn rồi."),
    ("一起", "yìqǐ", "cùng nhau", "一起吃饭。", "Cùng nhau ăn cơm."),
    ("一点儿", "yìdiǎnr", "một chút", "等一点儿。", "Đợi một chút."),
    ("真", "zhēn", "thật, thật sự", "真好吃。", "Thật ngon."),
    ("最", "zuì", "nhất", "最好的。", "Tốt nhất."),
    ("从", "cóng", "từ", "从家到学校。", "Từ nhà đến trường."),
    ("但是", "dànshì", "nhưng", "我累，但是开心。", "Tôi mệt nhưng vui."),
    ("因为", "yīnwèi", "bởi vì", "因为下雨。", "Bởi vì trời mưa."),
    ("所以", "suǒyǐ", "cho nên", "所以我没去。", "Cho nên tôi không đi."),
    ("可能", "kěnéng", "có thể, có lẽ", "可能下雨。", "Có thể trời mưa."),
    ("希望", "xīwàng", "hy vọng", "希望明天好。", "Hy vọng ngày mai tốt."),

    # Khác
    ("生日", "shēngrì", "sinh nhật", "今天我生日。", "Hôm nay sinh nhật tôi."),
    ("身体", "shēntǐ", "cơ thể", "身体健康。", "Sức khoẻ tốt."),
    ("药", "yào", "thuốc", "吃药。", "Uống thuốc."),
    ("颜色", "yánsè", "màu sắc", "什么颜色？", "Màu gì?"),
    ("题", "tí", "đề bài", "这道题难。", "Bài này khó."),
    ("课", "kè", "tiết học", "上课。", "Vào học."),
    ("汉语", "Hànyǔ", "tiếng Trung", "我学汉语。", "Tôi học tiếng Trung."),
    ("中国", "Zhōngguó", "Trung Quốc", "我去中国。", "Tôi đi Trung Quốc."),
    ("北京", "Běijīng", "Bắc Kinh", "北京很大。", "Bắc Kinh rất to."),
    ("字", "zì", "chữ", "汉字很难。", "Chữ Hán khó."),
    ("票", "piào", "vé", "买票。", "Mua vé."),
    ("月亮", "yuèliang", "mặt trăng", "月亮很圆。", "Trăng tròn."),
    ("太阳", "tàiyáng", "mặt trời", "太阳出来了。", "Mặt trời lên rồi."),
]

# ============================================================
# HSK 3 — ~300 từ (chỉ những từ MỚI ở cấp HSK 3, không trùng HSK 2)
# ============================================================
HSK3 = [
    # Đại từ & xưng hô
    ("自己", "zìjǐ", "bản thân, tự mình", "做自己。", "Hãy là chính mình."),
    ("别人", "biéren", "người khác", "别人不知道。", "Người khác không biết."),
    ("大家", "dàjiā", "mọi người", "大家好！", "Chào mọi người!"),
    ("其他", "qítā", "khác", "其他人来了。", "Người khác đến rồi."),
    ("自行车", "zìxíngchē", "xe đạp", "我骑自行车。", "Tôi đi xe đạp."),

    # Thời gian & tần suất
    ("最近", "zuìjìn", "gần đây", "最近怎么样？", "Gần đây thế nào?"),
    ("以后", "yǐhòu", "sau này", "以后再说。", "Sau này nói tiếp."),
    ("过去", "guòqù", "quá khứ; đi qua", "过去的事。", "Chuyện quá khứ."),
    ("将来", "jiānglái", "tương lai", "将来想做老师。", "Tương lai muốn làm giáo viên."),
    ("一直", "yìzhí", "luôn, suốt", "一直在学。", "Luôn học."),
    ("一边", "yìbiān", "vừa…vừa…", "一边吃一边看。", "Vừa ăn vừa xem."),
    ("一定", "yídìng", "nhất định", "一定来。", "Nhất định đến."),
    ("一般", "yìbān", "bình thường", "我一般早睡。", "Tôi thường ngủ sớm."),
    ("一会儿", "yíhuìr", "một lát", "等一会儿。", "Đợi một lát."),
    ("一样", "yíyàng", "giống nhau", "我们一样。", "Chúng tôi giống nhau."),
    ("总是", "zǒngshì", "luôn luôn", "他总是迟到。", "Anh ấy luôn đến muộn."),
    ("经常", "jīngcháng", "thường xuyên", "经常运动。", "Thường tập thể dục."),
    ("有时候", "yǒu shíhou", "thỉnh thoảng", "有时候看书。", "Thỉnh thoảng đọc sách."),
    ("从来", "cónglái", "từ trước đến nay", "我从来不喝酒。", "Tôi chưa từng uống rượu."),
    ("终于", "zhōngyú", "cuối cùng", "终于到了。", "Cuối cùng đến rồi."),
    ("刚才", "gāngcái", "vừa nãy", "刚才他来过。", "Vừa nãy anh ấy đến."),
    ("马上", "mǎshàng", "ngay lập tức", "马上来。", "Đến ngay."),
    ("突然", "tūrán", "đột nhiên", "突然下雨了。", "Đột nhiên trời mưa."),
    ("世纪", "shìjì", "thế kỷ", "二十一世纪。", "Thế kỷ 21."),
    ("季节", "jìjié", "mùa", "我喜欢春季。", "Tôi thích mùa xuân."),
    ("春", "chūn", "mùa xuân", "春天来了。", "Mùa xuân đến rồi."),
    ("夏", "xià", "mùa hè", "夏天很热。", "Mùa hè rất nóng."),
    ("秋", "qiū", "mùa thu", "秋天凉快。", "Mùa thu mát."),
    ("冬", "dōng", "mùa đông", "冬天下雪。", "Mùa đông có tuyết."),

    # Động từ
    ("练习", "liànxí", "luyện tập", "练习汉语。", "Luyện tập tiếng Trung."),
    ("教", "jiāo", "dạy", "老师教汉语。", "Cô giáo dạy tiếng Trung."),
    ("用", "yòng", "dùng", "用筷子吃饭。", "Dùng đũa ăn cơm."),
    ("解决", "jiějué", "giải quyết", "解决问题。", "Giải quyết vấn đề."),
    ("决定", "juédìng", "quyết định", "我决定去。", "Tôi quyết định đi."),
    ("选择", "xuǎnzé", "lựa chọn", "你选择哪个？", "Bạn chọn cái nào?"),
    ("照顾", "zhàogu", "chăm sóc", "照顾孩子。", "Chăm sóc trẻ con."),
    ("关心", "guānxīn", "quan tâm", "她很关心我。", "Cô ấy rất quan tâm tôi."),
    ("同意", "tóngyì", "đồng ý", "我同意你的话。", "Tôi đồng ý với bạn."),
    ("相信", "xiāngxìn", "tin tưởng", "我相信你。", "Tôi tin bạn."),
    ("发现", "fāxiàn", "phát hiện", "发现一个秘密。", "Phát hiện một bí mật."),
    ("注意", "zhùyì", "chú ý", "请注意安全。", "Xin chú ý an toàn."),
    ("记得", "jìde", "nhớ", "我记得你。", "Tôi nhớ bạn."),
    ("忘记", "wàngjì", "quên", "我忘记了。", "Tôi quên rồi."),
    ("习惯", "xíguàn", "thói quen, quen", "习惯早起。", "Quen dậy sớm."),
    ("提高", "tígāo", "nâng cao", "提高水平。", "Nâng cao trình độ."),
    ("结束", "jiéshù", "kết thúc", "会议结束。", "Cuộc họp kết thúc."),
    ("开始", "kāishǐ", "bắt đầu", "开始上课。", "Bắt đầu học."),
    ("继续", "jìxù", "tiếp tục", "继续努力。", "Tiếp tục cố gắng."),
    ("完成", "wánchéng", "hoàn thành", "完成作业。", "Hoàn thành bài tập."),
    ("参加", "cānjiā", "tham gia", "参加比赛。", "Tham gia thi đấu."),
    ("欢迎", "huānyíng", "chào đón", "欢迎光临。", "Hoan nghênh quý khách."),
    ("举行", "jǔxíng", "tổ chức", "举行会议。", "Tổ chức cuộc họp."),
    ("放", "fàng", "đặt, để; thả", "放在桌子上。", "Đặt lên bàn."),
    ("拿", "ná", "cầm, lấy", "拿钱包。", "Cầm ví."),
    ("接", "jiē", "đón, nhận", "去机场接她。", "Ra sân bay đón cô ấy."),
    ("搬", "bān", "chuyển, dời", "搬家。", "Chuyển nhà."),
    ("借", "jiè", "mượn, cho mượn", "借我一本书。", "Cho tôi mượn quyển sách."),
    ("还", "huán", "trả lại", "还书。", "Trả sách."),
    ("付", "fù", "trả (tiền)", "付钱。", "Trả tiền."),
    ("花", "huā", "tiêu, dùng", "花了很多钱。", "Tiêu rất nhiều tiền."),
    ("骑", "qí", "cưỡi, đi (xe đạp)", "骑自行车。", "Đi xe đạp."),
    ("过", "guò", "qua, đi qua", "过马路。", "Qua đường."),
    ("离开", "líkāi", "rời khỏi", "离开北京。", "Rời Bắc Kinh."),
    ("到达", "dàodá", "đến nơi", "到达机场。", "Đến sân bay."),
    ("出发", "chūfā", "xuất phát", "明天出发。", "Mai xuất phát."),
    ("迟到", "chídào", "đến muộn", "上课迟到了。", "Đến lớp muộn."),
    ("等候", "děnghòu", "đợi chờ", "等候朋友。", "Đợi chờ bạn."),
    ("感谢", "gǎnxiè", "cảm ơn (trang trọng)", "感谢您的帮助。", "Cảm ơn sự giúp đỡ của ngài."),
    ("祝", "zhù", "chúc", "祝你成功！", "Chúc bạn thành công!"),
    ("放心", "fàngxīn", "yên tâm", "你放心吧。", "Bạn yên tâm đi."),
    ("担心", "dānxīn", "lo lắng", "别担心。", "Đừng lo."),
    ("生气", "shēngqì", "tức giận", "他生气了。", "Anh ấy tức giận rồi."),
    ("哭", "kū", "khóc", "孩子在哭。", "Trẻ con đang khóc."),
    ("笑", "xiào", "cười", "她在笑。", "Cô ấy đang cười."),
    ("聊天", "liáotiān", "tán gẫu", "我们聊天吧。", "Chúng ta tán gẫu nhé."),
    ("讨论", "tǎolùn", "thảo luận", "讨论问题。", "Thảo luận vấn đề."),
    ("介绍", "jièshào", "giới thiệu", "介绍朋友。", "Giới thiệu bạn."),
    ("表示", "biǎoshì", "biểu thị, bày tỏ", "表示感谢。", "Bày tỏ cảm ơn."),
    ("发", "fā", "gửi, phát", "发邮件。", "Gửi email."),
    ("收", "shōu", "nhận", "收信。", "Nhận thư."),
    ("寄", "jì", "gửi (qua bưu điện)", "寄信。", "Gửi thư."),
    ("回来", "huílái", "trở về", "他回来了。", "Anh ấy về rồi."),
    ("出去", "chūqù", "đi ra ngoài", "我出去一下。", "Tôi ra ngoài một chút."),
    ("回去", "huíqù", "trở về", "我回去了。", "Tôi về đây."),
    ("过来", "guòlái", "lại đây", "请过来。", "Mời đến đây."),
    ("起来", "qǐlái", "đứng dậy", "请起来。", "Xin đứng dậy."),
    ("下来", "xiàlái", "xuống", "下来吧。", "Xuống đi."),
    ("上去", "shàngqù", "đi lên", "上去看看。", "Lên xem thử."),
    ("张", "zhāng", "tờ (lượng từ)", "一张纸。", "Một tờ giấy."),
    ("把", "bǎ", "lượng từ; giới từ", "把门关上。", "Đóng cửa lại."),
    ("辆", "liàng", "chiếc (xe)", "一辆车。", "Một chiếc xe."),
    ("条", "tiáo", "cái (dài, mảnh)", "一条河。", "Một con sông."),
    ("位", "wèi", "vị (lượng từ trang trọng)", "一位老师。", "Một vị giáo viên."),
    ("种", "zhǒng", "loại", "这种水果。", "Loại trái cây này."),
    ("段", "duàn", "đoạn", "一段时间。", "Một đoạn thời gian."),
    ("公斤", "gōngjīn", "kilogam", "五公斤苹果。", "5 kg táo."),
    ("米", "mǐ", "mét", "一米长。", "Dài một mét."),
    ("元", "yuán", "đồng (NDT)", "一百元。", "Một trăm tệ."),
    ("角", "jiǎo", "hào", "五角钱。", "Năm hào."),

    # Tính từ & trạng thái
    ("简单", "jiǎndān", "đơn giản", "问题很简单。", "Vấn đề đơn giản."),
    ("复杂", "fùzá", "phức tạp", "事情很复杂。", "Việc rất phức tạp."),
    ("容易", "róngyì", "dễ", "汉语不容易。", "Tiếng Trung không dễ."),
    ("难", "nán", "khó", "考试很难。", "Bài thi rất khó."),
    ("好像", "hǎoxiàng", "hình như", "好像下雨了。", "Hình như trời mưa."),
    ("重要", "zhòngyào", "quan trọng", "这很重要。", "Cái này rất quan trọng."),
    ("特别", "tèbié", "đặc biệt", "今天特别冷。", "Hôm nay đặc biệt lạnh."),
    ("奇怪", "qíguài", "kỳ lạ", "他很奇怪。", "Anh ấy kỳ lạ."),
    ("有名", "yǒumíng", "nổi tiếng", "她很有名。", "Cô ấy rất nổi tiếng."),
    ("聪明", "cōngming", "thông minh", "孩子很聪明。", "Trẻ rất thông minh."),
    ("健康", "jiànkāng", "khoẻ mạnh", "祝你健康。", "Chúc bạn khoẻ mạnh."),
    ("舒服", "shūfu", "thoải mái", "我不舒服。", "Tôi không khoẻ."),
    ("方便", "fāngbiàn", "thuận tiện", "很方便。", "Rất thuận tiện."),
    ("安全", "ānquán", "an toàn", "注意安全。", "Chú ý an toàn."),
    ("满意", "mǎnyì", "hài lòng", "我很满意。", "Tôi rất hài lòng."),
    ("难过", "nánguò", "buồn", "她很难过。", "Cô ấy rất buồn."),
    ("热情", "rèqíng", "nhiệt tình", "他很热情。", "Anh ấy rất nhiệt tình."),
    ("年轻", "niánqīng", "trẻ", "他很年轻。", "Anh ấy còn trẻ."),
    ("胖", "pàng", "béo", "他胖了。", "Anh ấy béo lên."),
    ("瘦", "shòu", "gầy", "她很瘦。", "Cô ấy rất gầy."),
    ("矮", "ǎi", "thấp (chiều cao)", "他个子矮。", "Anh ấy thấp."),
    ("饿", "è", "đói", "我饿了。", "Tôi đói rồi."),
    ("渴", "kě", "khát", "我很渴。", "Tôi rất khát."),
    ("饱", "bǎo", "no", "我吃饱了。", "Tôi ăn no rồi."),
    ("干净", "gānjìng", "sạch sẽ", "房间干净。", "Phòng sạch sẽ."),
    ("脏", "zāng", "bẩn", "衣服脏了。", "Quần áo bẩn."),
    ("亮", "liàng", "sáng", "灯很亮。", "Đèn rất sáng."),
    ("黑暗", "hēi'àn", "tối tăm", "屋子很黑暗。", "Phòng rất tối."),
    ("安静", "ānjìng", "yên tĩnh", "请安静。", "Xin yên lặng."),
    ("热闹", "rènào", "náo nhiệt", "市场很热闹。", "Chợ rất náo nhiệt."),
    ("有趣", "yǒuqù", "thú vị", "电影很有趣。", "Phim rất thú vị."),
    ("一般", "yìbān", "bình thường", "成绩一般。", "Thành tích bình thường."),
    ("满", "mǎn", "đầy", "杯子是满的。", "Cốc đầy."),
    ("空", "kōng", "rỗng, trống", "盒子是空的。", "Hộp rỗng."),
    ("饿", "è", "đói", "肚子饿。", "Bụng đói."),

    # Sự vật & nơi chốn
    ("公园", "gōngyuán", "công viên", "去公园散步。", "Đi công viên dạo."),
    ("银行", "yínháng", "ngân hàng", "去银行取钱。", "Đến ngân hàng rút tiền."),
    ("超市", "chāoshì", "siêu thị", "去超市买东西。", "Đi siêu thị mua đồ."),
    ("图书馆", "túshūguǎn", "thư viện", "在图书馆学习。", "Học ở thư viện."),
    ("饭馆", "fànguǎn", "quán ăn", "在饭馆吃饭。", "Ăn ở quán."),
    ("地铁", "dìtiě", "tàu điện ngầm", "坐地铁。", "Đi tàu điện ngầm."),
    ("船", "chuán", "thuyền, tàu thuỷ", "坐船。", "Đi thuyền."),
    ("地图", "dìtú", "bản đồ", "看地图。", "Xem bản đồ."),
    ("城市", "chéngshì", "thành phố", "大城市。", "Thành phố lớn."),
    ("国家", "guójiā", "quốc gia", "我爱我的国家。", "Tôi yêu đất nước mình."),
    ("世界", "shìjiè", "thế giới", "世界很大。", "Thế giới rất lớn."),
    ("地方", "dìfang", "nơi, chỗ", "这个地方。", "Nơi này."),
    ("环境", "huánjìng", "môi trường", "保护环境。", "Bảo vệ môi trường."),
    ("空气", "kōngqì", "không khí", "空气好。", "Không khí trong lành."),
    ("阳光", "yángguāng", "ánh nắng", "阳光很好。", "Nắng đẹp."),
    ("月", "yuè", "trăng", "月亮真圆。", "Trăng thật tròn."),
    ("星", "xīng", "ngôi sao", "天上有星星。", "Trên trời có sao."),
    ("河", "hé", "sông", "这条河很长。", "Con sông này dài."),
    ("山", "shān", "núi", "爬山。", "Leo núi."),
    ("树", "shù", "cây", "树很高。", "Cây rất cao."),
    ("花", "huā", "hoa", "花很漂亮。", "Hoa rất đẹp."),
    ("草", "cǎo", "cỏ", "草地。", "Bãi cỏ."),
    ("声音", "shēngyīn", "âm thanh", "声音太大。", "Âm thanh to quá."),
    ("照片", "zhàopiàn", "ảnh", "拍照片。", "Chụp ảnh."),
    ("礼物", "lǐwù", "quà", "送礼物。", "Tặng quà."),
    ("花园", "huāyuán", "vườn hoa", "花园很漂亮。", "Vườn rất đẹp."),
    ("厨房", "chúfáng", "nhà bếp", "在厨房做饭。", "Nấu cơm ở bếp."),
    ("空调", "kōngtiáo", "điều hoà", "开空调。", "Bật điều hoà."),
    ("冰箱", "bīngxiāng", "tủ lạnh", "冰箱里有水。", "Trong tủ lạnh có nước."),
    ("洗手间", "xǐshǒujiān", "phòng vệ sinh", "洗手间在哪儿？", "Toilet ở đâu?"),
    ("电梯", "diàntī", "thang máy", "坐电梯。", "Đi thang máy."),

    # Thức ăn & đồ uống
    ("菜", "cài", "món ăn, rau", "中国菜很好吃。", "Món Trung Quốc ngon."),
    ("肉", "ròu", "thịt", "我喜欢吃肉。", "Tôi thích ăn thịt."),
    ("饺子", "jiǎozi", "sủi cảo", "我会包饺子。", "Tôi biết gói sủi cảo."),
    ("面包", "miànbāo", "bánh mì", "吃面包。", "Ăn bánh mì."),
    ("蛋糕", "dàngāo", "bánh kem", "生日蛋糕。", "Bánh sinh nhật."),
    ("糖", "táng", "đường, kẹo", "加点糖。", "Thêm chút đường."),
    ("盐", "yán", "muối", "加点盐。", "Thêm chút muối."),
    ("香蕉", "xiāngjiāo", "chuối", "吃香蕉。", "Ăn chuối."),
    ("葡萄", "pútáo", "nho", "葡萄很甜。", "Nho rất ngọt."),
    ("啤酒", "píjiǔ", "bia", "喝啤酒。", "Uống bia."),
    ("饮料", "yǐnliào", "đồ uống", "买饮料。", "Mua đồ uống."),
    ("筷子", "kuàizi", "đũa", "用筷子吃饭。", "Dùng đũa ăn cơm."),
    ("盘子", "pánzi", "đĩa", "洗盘子。", "Rửa đĩa."),
    ("碗", "wǎn", "bát", "一碗饭。", "Một bát cơm."),
    ("杯子", "bēizi", "cốc", "一杯水。", "Một cốc nước."),
    ("勺子", "sháozi", "thìa", "用勺子。", "Dùng thìa."),

    # Quần áo & đồ dùng
    ("衣服", "yīfu", "quần áo", "买衣服。", "Mua quần áo."),
    ("裙子", "qúnzi", "váy", "穿裙子。", "Mặc váy."),
    ("裤子", "kùzi", "quần", "买裤子。", "Mua quần."),
    ("衬衫", "chènshān", "áo sơ mi", "白衬衫。", "Áo sơ mi trắng."),
    ("帽子", "màozi", "mũ", "戴帽子。", "Đội mũ."),
    ("鞋", "xié", "giày", "买鞋。", "Mua giày."),
    ("眼镜", "yǎnjìng", "kính mắt", "戴眼镜。", "Đeo kính."),
    ("行李箱", "xínglixiāng", "vali", "拉行李箱。", "Kéo vali."),
    ("照相机", "zhàoxiàngjī", "máy ảnh", "用照相机。", "Dùng máy ảnh."),
    ("钱包", "qiánbāo", "ví tiền", "我的钱包。", "Ví của tôi."),
    ("伞", "sǎn", "ô, dù", "下雨带伞。", "Mưa mang ô."),
    ("地图", "dìtú", "bản đồ", "看地图。", "Xem bản đồ."),
    ("信用卡", "xìnyòngkǎ", "thẻ tín dụng", "用信用卡。", "Dùng thẻ tín dụng."),
    ("行李", "xíngli", "hành lý", "整理行李。", "Sắp xếp hành lý."),

    # Cảm xúc & quan hệ
    ("感动", "gǎndòng", "cảm động", "我很感动。", "Tôi rất cảm động."),
    ("感觉", "gǎnjué", "cảm giác", "感觉很好。", "Cảm giác rất tốt."),
    ("感情", "gǎnqíng", "tình cảm", "感情很深。", "Tình cảm sâu sắc."),
    ("爱好", "àihào", "sở thích", "我的爱好是看书。", "Sở thích của tôi là đọc sách."),
    ("兴趣", "xìngqù", "hứng thú", "对音乐有兴趣。", "Có hứng thú với âm nhạc."),
    ("信", "xìn", "thư; tin", "写信。", "Viết thư."),
    ("电子邮件", "diànzǐ yóujiàn", "email", "发电子邮件。", "Gửi email."),
    ("文化", "wénhuà", "văn hoá", "中国文化。", "Văn hoá Trung Quốc."),
    ("历史", "lìshǐ", "lịch sử", "学历史。", "Học lịch sử."),
    ("音乐", "yīnyuè", "âm nhạc", "听音乐。", "Nghe nhạc."),
    ("电影", "diànyǐng", "phim", "看电影。", "Xem phim."),
    ("故事", "gùshi", "câu chuyện", "讲故事。", "Kể chuyện."),
    ("新闻", "xīnwén", "tin tức", "看新闻。", "Xem tin tức."),
    ("游戏", "yóuxì", "trò chơi", "玩游戏。", "Chơi trò chơi."),
    ("运动", "yùndòng", "thể thao", "做运动。", "Tập thể thao."),
    ("足球", "zúqiú", "bóng đá", "踢足球。", "Đá bóng."),
    ("篮球", "lánqiú", "bóng rổ", "打篮球。", "Chơi bóng rổ."),
    ("乒乓球", "pīngpāngqiú", "bóng bàn", "打乒乓球。", "Chơi bóng bàn."),

    # Học tập & công việc
    ("成绩", "chéngjì", "thành tích", "成绩很好。", "Thành tích tốt."),
    ("考试", "kǎoshì", "kỳ thi", "明天考试。", "Mai có kỳ thi."),
    ("作业", "zuòyè", "bài tập", "做作业。", "Làm bài tập."),
    ("练习", "liànxí", "bài luyện", "做练习。", "Làm bài luyện."),
    ("成功", "chénggōng", "thành công", "祝你成功。", "Chúc bạn thành công."),
    ("失败", "shībài", "thất bại", "失败是成功之母。", "Thất bại là mẹ thành công."),
    ("努力", "nǔlì", "nỗ lực", "努力学习。", "Nỗ lực học."),
    ("机会", "jīhuì", "cơ hội", "好机会。", "Cơ hội tốt."),
    ("水平", "shuǐpíng", "trình độ", "汉语水平高。", "Trình độ tiếng Trung cao."),
    ("能力", "nénglì", "năng lực", "工作能力强。", "Năng lực làm việc tốt."),
    ("会议", "huìyì", "cuộc họp", "开会议。", "Mở cuộc họp."),
    ("校长", "xiàozhǎng", "hiệu trưởng", "校长讲话。", "Hiệu trưởng phát biểu."),
    ("经理", "jīnglǐ", "giám đốc", "李经理。", "Giám đốc Lý."),
    ("办公室", "bàngōngshì", "văn phòng", "在办公室工作。", "Làm việc ở văn phòng."),
    ("职业", "zhíyè", "nghề nghiệp", "你的职业？", "Nghề của bạn?"),
    ("老板", "lǎobǎn", "ông chủ", "老板很好。", "Ông chủ tốt."),
    ("同事", "tóngshì", "đồng nghiệp", "我的同事。", "Đồng nghiệp của tôi."),

    # Sức khoẻ & y tế
    ("发烧", "fāshāo", "sốt", "孩子发烧。", "Trẻ bị sốt."),
    ("感冒", "gǎnmào", "cảm lạnh", "我感冒了。", "Tôi bị cảm."),
    ("疼", "téng", "đau", "头疼。", "Đau đầu."),
    ("生病", "shēngbìng", "bệnh", "他生病了。", "Anh ấy bệnh rồi."),
    ("锻炼", "duànliàn", "rèn luyện", "锻炼身体。", "Rèn luyện cơ thể."),
    ("休息", "xiūxi", "nghỉ ngơi", "休息一下。", "Nghỉ một lát."),
    ("减肥", "jiǎnféi", "giảm cân", "我要减肥。", "Tôi muốn giảm cân."),

    # Mua sắm
    ("便宜", "piányi", "rẻ", "这个便宜。", "Cái này rẻ."),
    ("打折", "dǎzhé", "giảm giá", "打八折。", "Giảm 20%."),
    ("超市", "chāoshì", "siêu thị", "去超市。", "Đi siêu thị."),
    ("付款", "fùkuǎn", "thanh toán", "付款方式。", "Phương thức thanh toán."),
    ("送货", "sònghuò", "giao hàng", "免费送货。", "Miễn phí giao hàng."),

    # Liên từ, giới từ, trợ từ
    ("如果", "rúguǒ", "nếu", "如果下雨，我不去。", "Nếu trời mưa, tôi không đi."),
    ("虽然", "suīrán", "tuy", "虽然累，但很快乐。", "Tuy mệt nhưng rất vui."),
    ("还是", "háishi", "hay là", "茶还是咖啡？", "Trà hay cà phê?"),
    ("或者", "huòzhě", "hoặc", "茶或者咖啡都行。", "Trà hoặc cà phê đều được."),
    ("只", "zhǐ", "chỉ", "只有一个。", "Chỉ có một cái."),
    ("只要", "zhǐyào", "chỉ cần", "只要努力就行。", "Chỉ cần cố gắng là được."),
    ("除了", "chúle", "ngoài", "除了我都去。", "Ngoài tôi ra đều đi."),
    ("除非", "chúfēi", "trừ phi", "除非你去。", "Trừ phi bạn đi."),
    ("被", "bèi", "bị, được", "杯子被打破了。", "Cốc bị vỡ."),
    ("比", "bǐ", "so với", "我比他高。", "Tôi cao hơn anh ấy."),
    ("一边", "yìbiān", "một bên", "一边一个。", "Mỗi bên một cái."),
    ("更", "gèng", "càng, hơn", "今天更冷。", "Hôm nay càng lạnh."),
    ("越", "yuè", "càng", "越多越好。", "Càng nhiều càng tốt."),
    ("为", "wèi", "vì", "为你高兴。", "Mừng cho bạn."),
    ("为了", "wèile", "để, vì", "为了健康。", "Vì sức khoẻ."),
    ("对", "duì", "đối với", "对我重要。", "Quan trọng với tôi."),
    ("着", "zhe", "trợ từ thể tiếp diễn", "门开着。", "Cửa đang mở."),
    ("过", "guò", "trợ từ thể đã từng", "我去过中国。", "Tôi đã từng đến TQ."),
    ("了", "le", "trợ từ hoàn thành", "我吃了饭。", "Tôi đã ăn cơm."),
    ("吗", "ma", "trợ từ nghi vấn", "你好吗？", "Bạn khoẻ không?"),
    ("呢", "ne", "trợ từ nhấn mạnh", "你呢？", "Còn bạn thì sao?"),
    ("吧", "ba", "trợ từ đề nghị", "去吧。", "Đi nào."),

    # Phương vị nâng cao
    ("中", "zhōng", "giữa, trong", "心中。", "Trong lòng."),
    ("北方", "běifāng", "phía bắc", "中国北方。", "Phía bắc Trung Quốc."),
    ("南方", "nánfāng", "phía nam", "南方很热。", "Phía nam rất nóng."),
    ("东", "dōng", "đông", "东边。", "Phía đông."),
    ("西", "xī", "tây", "西边。", "Phía tây."),
    ("附近", "fùjìn", "gần đó", "附近有银行。", "Gần đây có ngân hàng."),
    ("周围", "zhōuwéi", "xung quanh", "学校周围。", "Xung quanh trường."),

    # Khác
    ("小心", "xiǎoxīn", "cẩn thận", "小心车。", "Cẩn thận xe."),
    ("奇迹", "qíjì", "kỳ tích", "这是奇迹。", "Đây là kỳ tích."),
    ("着急", "zháojí", "sốt ruột", "别着急。", "Đừng sốt ruột."),
    ("应该", "yīnggāi", "nên", "你应该去。", "Bạn nên đi."),
    ("必须", "bìxū", "phải, bắt buộc", "必须努力。", "Phải nỗ lực."),
    ("需要", "xūyào", "cần", "我需要帮助。", "Tôi cần giúp đỡ."),
    ("愿意", "yuànyì", "sẵn lòng", "我愿意帮你。", "Tôi sẵn lòng giúp bạn."),
    ("敢", "gǎn", "dám", "我不敢说。", "Tôi không dám nói."),
    ("数字", "shùzì", "con số", "记数字。", "Nhớ số."),
    ("中文", "Zhōngwén", "Trung văn", "学中文。", "Học tiếng Trung."),
    ("英文", "Yīngwén", "tiếng Anh", "说英文。", "Nói tiếng Anh."),
    ("自然", "zìrán", "tự nhiên", "热爱自然。", "Yêu thiên nhiên."),
    ("根据", "gēnjù", "căn cứ", "根据规定。", "Căn cứ quy định."),
    ("其实", "qíshí", "thực ra", "其实他很好。", "Thực ra anh ấy tốt."),
    ("当然", "dāngrán", "đương nhiên", "当然可以。", "Đương nhiên được."),
    ("可是", "kěshì", "nhưng", "可是我没空。", "Nhưng tôi không rảnh."),
    ("然后", "ránhòu", "sau đó", "然后回家。", "Sau đó về nhà."),
    ("不但", "búdàn", "không những", "不但聪明，而且努力。", "Không những thông minh, còn nỗ lực."),
    ("而且", "érqiě", "hơn nữa", "好吃而且便宜。", "Ngon và rẻ."),
    ("于是", "yúshì", "thế là", "于是我去了。", "Thế là tôi đi."),
    ("地", "de", "trợ từ trạng ngữ", "高兴地说。", "Nói vui vẻ."),
    ("得", "de", "trợ từ bổ ngữ", "跑得快。", "Chạy nhanh."),
    ("最好", "zuìhǎo", "tốt nhất là", "最好早点睡。", "Tốt nhất nên ngủ sớm."),
    ("差", "chà", "kém, thiếu", "差五分钟三点。", "Thiếu 5 phút nữa là 3 giờ."),
    ("满", "mǎn", "đầy", "杯子满了。", "Cốc đầy rồi."),
    ("方法", "fāngfǎ", "phương pháp", "学习方法。", "Phương pháp học."),
    ("办法", "bànfǎ", "cách, biện pháp", "想办法。", "Nghĩ cách."),
    ("规定", "guīdìng", "quy định", "公司规定。", "Quy định công ty."),
    ("习惯", "xíguàn", "quen", "习惯了。", "Quen rồi."),
    ("意思", "yìsi", "ý nghĩa", "什么意思？", "Nghĩa là gì?"),
    ("地址", "dìzhǐ", "địa chỉ", "你的地址？", "Địa chỉ của bạn?"),
    ("电子邮箱", "diànzǐ yóuxiāng", "hộp thư điện tử", "电子邮箱地址。", "Địa chỉ email."),
    ("黑板", "hēibǎn", "bảng đen", "看黑板。", "Nhìn bảng."),
    ("铅笔", "qiānbǐ", "bút chì", "用铅笔写。", "Viết bằng bút chì."),
    ("字典", "zìdiǎn", "từ điển", "查字典。", "Tra từ điển."),
]


# ============================================================
# HSK 4 — ~600 từ (chỉ những từ MỚI ở cấp HSK 4, không trùng HSK 2/3)
# ============================================================
HSK4 = [
    # ─── Đại từ & xưng hô ──────────────────────────
    ("任何", "rènhé", "bất kỳ", "任何人都可以参加。", "Bất kỳ ai cũng có thể tham gia."),
    ("个人", "gèrén", "cá nhân", "个人意见。", "Ý kiến cá nhân."),
    ("人民", "rénmín", "nhân dân", "人民的力量。", "Sức mạnh nhân dân."),
    ("人口", "rénkǒu", "dân số", "人口很多。", "Dân số rất đông."),
    ("人类", "rénlèi", "loài người", "人类的未来。", "Tương lai loài người."),
    ("民族", "mínzú", "dân tộc", "中华民族。", "Dân tộc Trung Hoa."),
    ("作者", "zuòzhě", "tác giả", "这本书的作者。", "Tác giả quyển sách này."),
    ("观众", "guānzhòng", "khán giả", "观众很多。", "Khán giả rất đông."),
    ("亲戚", "qīnqi", "họ hàng", "我的亲戚。", "Họ hàng của tôi."),
    ("邻居", "línjū", "hàng xóm", "好邻居。", "Hàng xóm tốt."),
    ("夫妻", "fūqī", "vợ chồng", "他们是夫妻。", "Họ là vợ chồng."),
    ("孙子", "sūnzi", "cháu trai", "我的孙子。", "Cháu trai tôi."),
    ("孙女", "sūnnǚ", "cháu gái", "我的孙女。", "Cháu gái tôi."),
    ("叔叔", "shūshu", "chú", "我叔叔。", "Chú tôi."),
    ("阿姨", "āyí", "dì, cô", "李阿姨。", "Cô Lý."),
    ("青年", "qīngnián", "thanh niên", "青年人。", "Thanh niên."),
    ("成人", "chéngrén", "người lớn", "成人票。", "Vé người lớn."),
    ("儿童", "értóng", "thiếu nhi", "儿童节。", "Ngày thiếu nhi."),
    ("男性", "nánxìng", "nam giới", "男性朋友。", "Bạn nam."),
    ("女性", "nǚxìng", "nữ giới", "女性朋友。", "Bạn nữ."),

    # ─── Thời gian & trạng từ ──────────────────────
    ("年代", "niándài", "thời đại, niên đại", "六十年代。", "Thập niên 60."),
    ("时代", "shídài", "thời đại", "新时代。", "Thời đại mới."),
    ("时期", "shíqī", "thời kỳ", "重要时期。", "Thời kỳ quan trọng."),
    ("时刻", "shíkè", "thời khắc", "重要时刻。", "Thời khắc quan trọng."),
    ("瞬间", "shùnjiān", "khoảnh khắc", "美好瞬间。", "Khoảnh khắc đẹp."),
    ("即将", "jíjiāng", "sắp", "即将出发。", "Sắp xuất phát."),
    ("立即", "lìjí", "lập tức", "立即行动。", "Hành động ngay."),
    ("立刻", "lìkè", "lập tức", "立刻出发。", "Lập tức xuất phát."),
    ("及时", "jíshí", "kịp thời", "及时帮助。", "Giúp đỡ kịp thời."),
    ("逐渐", "zhújiàn", "dần dần", "逐渐变好。", "Dần dần tốt lên."),
    ("渐渐", "jiànjiàn", "từ từ", "渐渐熟悉。", "Dần dần quen."),
    ("永远", "yǒngyuǎn", "mãi mãi", "永远爱你。", "Mãi yêu bạn."),
    ("从此", "cóngcǐ", "từ đó", "从此分开。", "Từ đó chia xa."),
    ("从来", "cónglái", "từ trước đến nay", "从来没去过。", "Chưa từng đi."),
    ("曾经", "céngjīng", "đã từng", "我曾经爱过。", "Tôi đã từng yêu."),
    ("仍然", "réngrán", "vẫn", "仍然在等。", "Vẫn đang đợi."),
    ("依然", "yīrán", "vẫn", "依然如此。", "Vẫn như vậy."),
    ("照常", "zhàocháng", "như thường lệ", "照常营业。", "Mở cửa như thường."),
    ("到底", "dàodǐ", "rốt cuộc", "你到底想什么？", "Rốt cuộc bạn nghĩ gì?"),
    ("究竟", "jiūjìng", "rốt cuộc", "究竟为什么？", "Rốt cuộc tại sao?"),
    ("似乎", "sìhū", "dường như", "似乎下雨了。", "Dường như mưa."),
    ("仿佛", "fǎngfú", "tựa như", "仿佛做梦。", "Tựa như mơ."),
    ("差不多", "chàbuduō", "gần như", "差不多了。", "Gần xong rồi."),
    ("大约", "dàyuē", "khoảng", "大约十点。", "Khoảng 10 giờ."),
    ("大概", "dàgài", "đại khái", "大概知道。", "Đại khái biết."),
    ("约", "yuē", "khoảng, hẹn", "约一小时。", "Khoảng một giờ."),
    ("准时", "zhǔnshí", "đúng giờ", "准时到达。", "Đến đúng giờ."),
    ("按时", "ànshí", "đúng giờ", "按时上班。", "Đi làm đúng giờ."),

    # ─── Động từ ────────────────────────────────────
    ("适应", "shìyìng", "thích nghi", "适应环境。", "Thích nghi môi trường."),
    ("适合", "shìhé", "phù hợp", "适合你。", "Phù hợp với bạn."),
    ("符合", "fúhé", "phù hợp với", "符合标准。", "Phù hợp tiêu chuẩn."),
    ("满足", "mǎnzú", "thoả mãn", "满足要求。", "Thoả mãn yêu cầu."),
    ("达到", "dádào", "đạt đến", "达到目标。", "Đạt mục tiêu."),
    ("实现", "shíxiàn", "thực hiện, thành hiện thực", "实现梦想。", "Thực hiện ước mơ."),
    ("完善", "wánshàn", "hoàn thiện", "完善制度。", "Hoàn thiện chế độ."),
    ("发展", "fāzhǎn", "phát triển", "经济发展。", "Phát triển kinh tế."),
    ("发生", "fāshēng", "xảy ra", "发生了什么？", "Đã xảy ra chuyện gì?"),
    ("发挥", "fāhuī", "phát huy", "发挥能力。", "Phát huy năng lực."),
    ("发表", "fābiǎo", "phát biểu, công bố", "发表文章。", "Đăng bài."),
    ("成立", "chénglì", "thành lập", "公司成立了。", "Công ty được thành lập."),
    ("建立", "jiànlì", "xây dựng", "建立关系。", "Xây dựng quan hệ."),
    ("建设", "jiànshè", "xây dựng (lớn)", "建设国家。", "Xây dựng đất nước."),
    ("建议", "jiànyì", "đề nghị", "我建议你去。", "Tôi đề nghị bạn đi."),
    ("提出", "tíchū", "đưa ra", "提出意见。", "Đưa ra ý kiến."),
    ("提醒", "tíxǐng", "nhắc nhở", "提醒你一下。", "Nhắc bạn một chút."),
    ("提前", "tíqián", "trước thời hạn", "提前完成。", "Hoàn thành trước hạn."),
    ("推迟", "tuīchí", "hoãn lại", "推迟会议。", "Hoãn cuộc họp."),
    ("延长", "yáncháng", "kéo dài", "延长时间。", "Kéo dài thời gian."),
    ("缩短", "suōduǎn", "rút ngắn", "缩短时间。", "Rút ngắn thời gian."),
    ("增加", "zēngjiā", "tăng", "收入增加。", "Thu nhập tăng."),
    ("减少", "jiǎnshǎo", "giảm", "减少压力。", "Giảm áp lực."),
    ("降低", "jiàngdī", "hạ thấp", "降低价格。", "Hạ giá."),
    ("升级", "shēngjí", "nâng cấp", "系统升级。", "Hệ thống nâng cấp."),
    ("改变", "gǎibiàn", "thay đổi", "改变主意。", "Đổi ý."),
    ("改善", "gǎishàn", "cải thiện", "改善生活。", "Cải thiện cuộc sống."),
    ("改正", "gǎizhèng", "sửa đúng", "改正错误。", "Sửa sai."),
    ("修改", "xiūgǎi", "sửa đổi", "修改文章。", "Sửa bài."),
    ("修理", "xiūlǐ", "sửa chữa", "修理汽车。", "Sửa xe."),
    ("整理", "zhěnglǐ", "sắp xếp", "整理房间。", "Dọn phòng."),
    ("收拾", "shōushi", "thu dọn", "收拾东西。", "Thu dọn đồ."),
    ("准备", "zhǔnbèi", "chuẩn bị", "准备出门。", "Chuẩn bị ra ngoài."),
    ("安排", "ānpái", "sắp xếp, lên lịch", "安排时间。", "Sắp xếp thời gian."),
    ("计划", "jìhuà", "kế hoạch", "明年的计划。", "Kế hoạch năm sau."),
    ("打算", "dǎsuàn", "định, dự tính", "打算去中国。", "Định đi TQ."),
    ("考虑", "kǎolǜ", "cân nhắc", "考虑一下。", "Cân nhắc một chút."),
    ("商量", "shāngliang", "bàn bạc", "商量一下。", "Bàn một chút."),
    ("讨厌", "tǎoyàn", "ghét", "我讨厌这个。", "Tôi ghét cái này."),
    ("怀疑", "huáiyí", "nghi ngờ", "怀疑他。", "Nghi ngờ anh ta."),
    ("肯定", "kěndìng", "khẳng định", "我肯定。", "Tôi khẳng định."),
    ("否定", "fǒudìng", "phủ định", "否定意见。", "Phủ định ý kiến."),
    ("证明", "zhèngmíng", "chứng minh", "证明你的话。", "Chứng minh lời bạn."),
    ("说明", "shuōmíng", "giải thích", "说明原因。", "Giải thích lý do."),
    ("解释", "jiěshì", "giải thích", "请解释一下。", "Xin giải thích."),
    ("翻译", "fānyì", "phiên dịch", "翻译文章。", "Dịch bài."),
    ("发音", "fāyīn", "phát âm", "发音准确。", "Phát âm chuẩn."),
    ("阅读", "yuèdú", "đọc", "阅读书籍。", "Đọc sách."),
    ("背", "bèi", "thuộc; lưng", "背单词。", "Học thuộc từ."),
    ("复习", "fùxí", "ôn tập", "复习功课。", "Ôn bài."),
    ("预习", "yùxí", "chuẩn bị bài", "预习课文。", "Chuẩn bị bài đọc."),
    ("毕业", "bìyè", "tốt nghiệp", "大学毕业。", "Tốt nghiệp đại học."),
    ("入学", "rùxué", "nhập học", "九月入学。", "Nhập học tháng 9."),
    ("报名", "bàomíng", "đăng ký", "报名参加。", "Đăng ký tham gia."),
    ("签字", "qiānzì", "ký tên", "请签字。", "Xin ký tên."),
    ("申请", "shēnqǐng", "đăng ký, xin", "申请签证。", "Xin visa."),
    ("批准", "pīzhǔn", "phê chuẩn", "申请批准了。", "Đơn được phê chuẩn."),
    ("拒绝", "jùjué", "từ chối", "拒绝邀请。", "Từ chối lời mời."),
    ("接受", "jiēshòu", "chấp nhận", "接受现实。", "Chấp nhận sự thật."),
    ("收到", "shōudào", "nhận được", "收到礼物。", "Nhận được quà."),
    ("赢", "yíng", "thắng", "赢比赛。", "Thắng trận đấu."),
    ("输", "shū", "thua", "输了。", "Thua rồi."),
    ("放弃", "fàngqì", "từ bỏ", "不要放弃。", "Đừng bỏ cuộc."),
    ("坚持", "jiānchí", "kiên trì", "坚持下去。", "Kiên trì."),
    ("鼓励", "gǔlì", "khích lệ", "鼓励孩子。", "Khích lệ trẻ."),
    ("批评", "pīpíng", "phê bình", "批评错误。", "Phê bình sai sót."),
    ("表扬", "biǎoyáng", "khen ngợi", "老师表扬他。", "Cô khen anh ấy."),
    ("骂", "mà", "mắng", "妈妈骂我。", "Mẹ mắng tôi."),
    ("吵架", "chǎojià", "cãi nhau", "他们吵架了。", "Họ cãi nhau rồi."),
    ("道歉", "dàoqiàn", "xin lỗi", "我向你道歉。", "Tôi xin lỗi bạn."),
    ("原谅", "yuánliàng", "tha thứ", "请原谅我。", "Xin tha thứ cho tôi."),
    ("约会", "yuēhuì", "hẹn hò", "约会见面。", "Hẹn gặp nhau."),
    ("结婚", "jiéhūn", "kết hôn", "明年结婚。", "Năm sau kết hôn."),
    ("离婚", "líhūn", "ly hôn", "他们离婚了。", "Họ ly hôn rồi."),
    ("生", "shēng", "sinh, sống", "生孩子。", "Sinh con."),
    ("死", "sǐ", "chết", "他死了。", "Anh ấy mất rồi."),
    ("救", "jiù", "cứu", "救他一命。", "Cứu mạng anh ta."),
    ("陪", "péi", "đi cùng", "陪我去。", "Đi cùng tôi."),
    ("代表", "dàibiǎo", "đại diện", "代表公司。", "Đại diện công ty."),
    ("引起", "yǐnqǐ", "gây ra", "引起注意。", "Gây chú ý."),
    ("造成", "zàochéng", "gây ra (xấu)", "造成损失。", "Gây thiệt hại."),
    ("影响", "yǐngxiǎng", "ảnh hưởng", "影响很大。", "Ảnh hưởng lớn."),
    ("反映", "fǎnyìng", "phản ánh", "反映情况。", "Phản ánh tình hình."),
    ("反对", "fǎnduì", "phản đối", "反对意见。", "Phản đối ý kiến."),
    ("支持", "zhīchí", "ủng hộ", "支持你。", "Ủng hộ bạn."),
    ("信任", "xìnrèn", "tin cậy", "互相信任。", "Tin tưởng lẫn nhau."),
    ("尊重", "zūnzhòng", "tôn trọng", "尊重老师。", "Tôn trọng giáo viên."),
    ("保护", "bǎohù", "bảo vệ", "保护环境。", "Bảo vệ môi trường."),
    ("保证", "bǎozhèng", "đảm bảo", "我保证。", "Tôi đảm bảo."),
    ("保留", "bǎoliú", "giữ lại", "保留意见。", "Bảo lưu ý kiến."),
    ("保存", "bǎocún", "lưu giữ", "保存文件。", "Lưu file."),
    ("失去", "shīqù", "mất đi", "失去机会。", "Mất cơ hội."),
    ("丢", "diū", "mất, vứt", "丢钱包。", "Mất ví."),
    ("剩", "shèng", "còn lại", "剩下不多。", "Còn không nhiều."),
    ("掉", "diào", "rơi", "钥匙掉了。", "Chìa khoá rơi rồi."),
    ("摔", "shuāi", "ngã", "摔倒了。", "Ngã rồi."),
    ("撞", "zhuàng", "đụng, va", "撞车了。", "Đâm xe rồi."),
    ("敲", "qiāo", "gõ", "敲门。", "Gõ cửa."),
    ("举", "jǔ", "giơ lên", "举手。", "Giơ tay."),
    ("抓", "zhuā", "tóm, bắt", "抓机会。", "Nắm cơ hội."),
    ("挂", "guà", "treo, gọi (điện)", "挂电话。", "Cúp điện thoại."),
    ("拉", "lā", "kéo", "拉门。", "Kéo cửa."),
    ("推", "tuī", "đẩy", "推门。", "Đẩy cửa."),
    ("扔", "rēng", "ném, vứt", "扔垃圾。", "Vứt rác."),
    ("装", "zhuāng", "lắp; đựng; giả vờ", "装东西。", "Đựng đồ."),
    ("剪", "jiǎn", "cắt", "剪头发。", "Cắt tóc."),
    ("烧", "shāo", "đốt, nấu", "烧饭。", "Nấu cơm."),
    ("煮", "zhǔ", "luộc, nấu", "煮鸡蛋。", "Luộc trứng."),
    ("尝", "cháng", "nếm", "尝一下。", "Nếm thử."),
    ("闻", "wén", "ngửi", "闻一闻。", "Ngửi thử."),
    ("摸", "mō", "sờ, chạm", "别摸。", "Đừng chạm."),
    ("躺", "tǎng", "nằm", "躺在床上。", "Nằm trên giường."),
    ("抱", "bào", "ôm", "抱孩子。", "Bế con."),
    ("吻", "wěn", "hôn", "吻她。", "Hôn cô ấy."),
    ("醒", "xǐng", "tỉnh dậy", "我醒了。", "Tôi tỉnh rồi."),
    ("梦", "mèng", "mơ, giấc mơ", "做梦。", "Nằm mơ."),

    # ─── Tính từ & trạng thái ──────────────────────
    ("详细", "xiángxì", "chi tiết", "详细说明。", "Giải thích chi tiết."),
    ("仔细", "zǐxì", "kỹ càng", "仔细看。", "Xem kỹ."),
    ("准确", "zhǔnquè", "chính xác", "答案准确。", "Đáp án chính xác."),
    ("正确", "zhèngquè", "đúng đắn", "正确答案。", "Đáp án đúng."),
    ("错误", "cuòwù", "sai lầm", "犯了错误。", "Phạm sai lầm."),
    ("严格", "yángé", "nghiêm khắc", "老师很严格。", "Cô rất nghiêm."),
    ("严重", "yánzhòng", "nghiêm trọng", "情况严重。", "Tình hình nghiêm trọng."),
    ("严肃", "yánsù", "nghiêm túc", "严肃的态度。", "Thái độ nghiêm túc."),
    ("认真", "rènzhēn", "nghiêm túc, chăm chỉ", "认真学习。", "Học nghiêm túc."),
    ("积极", "jījí", "tích cực", "态度积极。", "Thái độ tích cực."),
    ("消极", "xiāojí", "tiêu cực", "消极态度。", "Thái độ tiêu cực."),
    ("主动", "zhǔdòng", "chủ động", "主动帮忙。", "Chủ động giúp."),
    ("被动", "bèidòng", "bị động", "被动接受。", "Bị động chấp nhận."),
    ("成熟", "chéngshú", "trưởng thành, chín", "他很成熟。", "Anh ấy chín chắn."),
    ("年纪", "niánjì", "tuổi tác", "年纪不大。", "Tuổi không lớn."),
    ("正式", "zhèngshì", "chính thức", "正式宣布。", "Tuyên bố chính thức."),
    ("非正式", "fēi zhèngshì", "không chính thức", "非正式会议。", "Họp không chính thức."),
    ("普通", "pǔtōng", "bình thường", "普通话。", "Tiếng phổ thông."),
    ("特殊", "tèshū", "đặc biệt", "特殊情况。", "Trường hợp đặc biệt."),
    ("一致", "yízhì", "thống nhất", "意见一致。", "Ý kiến thống nhất."),
    ("相同", "xiāngtóng", "giống nhau", "相同的爱好。", "Sở thích giống nhau."),
    ("不同", "bùtóng", "khác nhau", "不同的看法。", "Cách nhìn khác nhau."),
    ("相反", "xiāngfǎn", "ngược lại", "相反的方向。", "Hướng ngược lại."),
    ("相似", "xiāngsì", "tương tự", "相似的经验。", "Kinh nghiệm tương tự."),
    ("唯一", "wéiyī", "duy nhất", "唯一的选择。", "Lựa chọn duy nhất."),
    ("公平", "gōngpíng", "công bằng", "不公平。", "Không công bằng."),
    ("公共", "gōnggòng", "công cộng", "公共场所。", "Nơi công cộng."),
    ("个别", "gèbié", "cá biệt", "个别情况。", "Trường hợp cá biệt."),
    ("全部", "quánbù", "toàn bộ", "全部完成。", "Hoàn thành tất cả."),
    ("整个", "zhěnggè", "cả, toàn bộ", "整个房间。", "Cả căn phòng."),
    ("各", "gè", "mỗi, các", "各位。", "Các vị."),
    ("各种", "gèzhǒng", "đủ loại", "各种水果。", "Đủ loại trái cây."),
    ("丰富", "fēngfù", "phong phú", "经验丰富。", "Kinh nghiệm phong phú."),
    ("缺少", "quēshǎo", "thiếu", "缺少经验。", "Thiếu kinh nghiệm."),
    ("足够", "zúgòu", "đủ", "时间足够。", "Đủ thời gian."),
    ("充分", "chōngfèn", "đầy đủ", "充分准备。", "Chuẩn bị đầy đủ."),
    ("空闲", "kòngxián", "rảnh rỗi", "空闲时间。", "Thời gian rảnh."),
    ("紧张", "jǐnzhāng", "căng thẳng", "考试紧张。", "Thi căng thẳng."),
    ("放松", "fàngsōng", "thả lỏng", "放松一下。", "Thư giãn một chút."),
    ("轻松", "qīngsōng", "nhẹ nhàng", "轻松完成。", "Hoàn thành nhẹ nhàng."),
    ("艰难", "jiānnán", "gian nan", "艰难的日子。", "Những ngày gian nan."),
    ("困难", "kùnnán", "khó khăn", "困难的问题。", "Vấn đề khó khăn."),
    ("辛苦", "xīnkǔ", "vất vả", "工作辛苦。", "Công việc vất vả."),
    ("舒适", "shūshì", "dễ chịu", "舒适的房间。", "Phòng dễ chịu."),
    ("温暖", "wēnnuǎn", "ấm áp", "温暖的家。", "Mái nhà ấm."),
    ("凉快", "liángkuai", "mát mẻ", "今天凉快。", "Hôm nay mát."),
    ("湿", "shī", "ướt", "衣服湿了。", "Quần áo ướt."),
    ("干", "gān", "khô", "衣服干了。", "Quần áo khô."),
    ("软", "ruǎn", "mềm", "床很软。", "Giường mềm."),
    ("硬", "yìng", "cứng", "面包硬。", "Bánh mì cứng."),
    ("酸", "suān", "chua", "柠檬很酸。", "Chanh rất chua."),
    ("甜", "tián", "ngọt", "蛋糕很甜。", "Bánh ngọt."),
    ("苦", "kǔ", "đắng", "药很苦。", "Thuốc đắng."),
    ("辣", "là", "cay", "四川菜辣。", "Đồ Tứ Xuyên cay."),
    ("咸", "xián", "mặn", "汤太咸。", "Canh mặn quá."),
    ("淡", "dàn", "nhạt", "味道淡。", "Vị nhạt."),
    ("新鲜", "xīnxiān", "tươi", "蔬菜新鲜。", "Rau tươi."),
    ("好看", "hǎokàn", "đẹp (nhìn)", "她真好看。", "Cô ấy đẹp."),
    ("难看", "nánkàn", "xấu (nhìn)", "颜色难看。", "Màu xấu."),
    ("流行", "liúxíng", "thịnh hành", "流行歌曲。", "Bài hát thịnh hành."),
    ("熟", "shú", "chín, quen thuộc", "肉熟了。", "Thịt chín rồi."),
    ("陌生", "mòshēng", "xa lạ", "陌生人。", "Người lạ."),
    ("自由", "zìyóu", "tự do", "自由生活。", "Cuộc sống tự do."),
    ("自信", "zìxìn", "tự tin", "她很自信。", "Cô ấy tự tin."),
    ("骄傲", "jiāo'ào", "kiêu hãnh", "为他骄傲。", "Tự hào về anh ấy."),
    ("谦虚", "qiānxū", "khiêm tốn", "做人要谦虚。", "Làm người phải khiêm tốn."),
    ("懒", "lǎn", "lười", "他很懒。", "Anh ấy lười."),
    ("勤奋", "qínfèn", "siêng năng", "勤奋学习。", "Học siêng năng."),
    ("诚实", "chéngshí", "thành thật", "做人诚实。", "Sống thành thật."),
    ("勇敢", "yǒnggǎn", "dũng cảm", "他很勇敢。", "Anh ấy dũng cảm."),
    ("害羞", "hàixiū", "ngại ngùng", "她很害羞。", "Cô ấy hay ngại."),
    ("耐心", "nàixīn", "kiên nhẫn", "有耐心。", "Có kiên nhẫn."),
    ("粗心", "cūxīn", "cẩu thả", "他很粗心。", "Anh ấy cẩu thả."),
    ("幽默", "yōumò", "hài hước", "幽默的人。", "Người hài hước."),
    ("温柔", "wēnróu", "dịu dàng", "温柔的女孩。", "Cô gái dịu dàng."),
    ("浪漫", "làngmàn", "lãng mạn", "浪漫的晚餐。", "Bữa tối lãng mạn."),

    # ─── Sự vật & nơi chốn ─────────────────────────
    ("社会", "shèhuì", "xã hội", "社会发展。", "Xã hội phát triển."),
    ("政府", "zhèngfǔ", "chính phủ", "政府决定。", "Chính phủ quyết định."),
    ("法律", "fǎlǜ", "luật pháp", "遵守法律。", "Tuân thủ pháp luật."),
    ("规则", "guīzé", "quy tắc", "遵守规则。", "Tuân thủ quy tắc."),
    ("制度", "zhìdù", "chế độ", "管理制度。", "Chế độ quản lý."),
    ("政策", "zhèngcè", "chính sách", "新政策。", "Chính sách mới."),
    ("经济", "jīngjì", "kinh tế", "经济发展。", "Phát triển kinh tế."),
    ("市场", "shìchǎng", "thị trường", "去市场。", "Đi chợ."),
    ("生意", "shēngyi", "việc kinh doanh", "做生意。", "Kinh doanh."),
    ("商品", "shāngpǐn", "hàng hoá", "高质量商品。", "Hàng chất lượng cao."),
    ("产品", "chǎnpǐn", "sản phẩm", "新产品。", "Sản phẩm mới."),
    ("工厂", "gōngchǎng", "nhà máy", "在工厂工作。", "Làm việc ở nhà máy."),
    ("公里", "gōnglǐ", "kilômét", "十公里。", "Mười cây số."),
    ("地区", "dìqū", "khu vực", "南方地区。", "Khu vực phía Nam."),
    ("郊区", "jiāoqū", "ngoại ô", "住在郊区。", "Sống ngoại ô."),
    ("农村", "nóngcūn", "nông thôn", "农村风景。", "Cảnh nông thôn."),
    ("地球", "dìqiú", "trái đất", "保护地球。", "Bảo vệ trái đất."),
    ("自然", "zìrán", "tự nhiên", "大自然。", "Đại tự nhiên."),
    ("气候", "qìhòu", "khí hậu", "气候变化。", "Biến đổi khí hậu."),
    ("污染", "wūrǎn", "ô nhiễm", "空气污染。", "Ô nhiễm không khí."),
    ("垃圾", "lājī", "rác", "扔垃圾。", "Vứt rác."),
    ("能源", "néngyuán", "năng lượng", "节约能源。", "Tiết kiệm năng lượng."),
    ("石油", "shíyóu", "dầu mỏ", "石油价格。", "Giá dầu."),
    ("森林", "sēnlín", "rừng", "保护森林。", "Bảo vệ rừng."),
    ("沙漠", "shāmò", "sa mạc", "撒哈拉沙漠。", "Sa mạc Sahara."),
    ("湖", "hú", "hồ", "湖很美。", "Hồ rất đẹp."),
    ("海洋", "hǎiyáng", "đại dương", "保护海洋。", "Bảo vệ đại dương."),
    ("岛", "dǎo", "đảo", "去海岛旅行。", "Đi du lịch đảo."),
    ("石头", "shítou", "đá", "大石头。", "Tảng đá lớn."),
    ("土地", "tǔdì", "đất đai", "土地肥沃。", "Đất đai màu mỡ."),
    ("天空", "tiānkōng", "bầu trời", "蓝天空。", "Bầu trời xanh."),
    ("云", "yún", "mây", "天上有云。", "Trời có mây."),
    ("风", "fēng", "gió", "风很大。", "Gió to."),
    ("闪电", "shǎndiàn", "tia chớp", "打闪电。", "Có tia chớp."),
    ("雷", "léi", "sấm", "打雷了。", "Có sấm rồi."),
    ("温度", "wēndù", "nhiệt độ", "温度高。", "Nhiệt độ cao."),
    ("空", "kōng", "không, rỗng", "空房子。", "Nhà trống."),
    ("窗户", "chuānghu", "cửa sổ", "开窗户。", "Mở cửa sổ."),
    ("沙发", "shāfā", "ghế sofa", "坐在沙发上。", "Ngồi sofa."),
    ("床", "chuáng", "giường", "睡在床上。", "Ngủ trên giường."),
    ("墙", "qiáng", "tường", "墙上有画。", "Trên tường có tranh."),
    ("地板", "dìbǎn", "sàn nhà", "干净的地板。", "Sàn sạch."),
    ("天花板", "tiānhuābǎn", "trần nhà", "高的天花板。", "Trần cao."),
    ("镜子", "jìngzi", "gương", "照镜子。", "Soi gương."),
    ("毛巾", "máojīn", "khăn lau", "用毛巾。", "Dùng khăn."),
    ("肥皂", "féizào", "xà phòng", "用肥皂洗手。", "Rửa tay bằng xà phòng."),
    ("牙膏", "yágāo", "kem đánh răng", "买牙膏。", "Mua kem đánh răng."),
    ("洗衣机", "xǐyījī", "máy giặt", "用洗衣机。", "Dùng máy giặt."),
    ("微波炉", "wēibōlú", "lò vi sóng", "用微波炉。", "Dùng lò vi sóng."),

    # ─── Thức ăn & nông sản ────────────────────────
    ("食物", "shíwù", "thức ăn", "新鲜食物。", "Đồ ăn tươi."),
    ("食品", "shípǐn", "thực phẩm", "进口食品。", "Thực phẩm nhập khẩu."),
    ("蔬菜", "shūcài", "rau", "吃蔬菜。", "Ăn rau."),
    ("水果", "shuǐguǒ", "trái cây", "新鲜水果。", "Trái cây tươi."),
    ("橘子", "júzi", "quýt", "橘子甜。", "Quýt ngọt."),
    ("草莓", "cǎoméi", "dâu tây", "我爱草莓。", "Tôi yêu dâu."),
    ("梨", "lí", "lê", "梨很甜。", "Lê ngọt."),
    ("猪肉", "zhūròu", "thịt heo", "买猪肉。", "Mua thịt heo."),
    ("牛肉", "niúròu", "thịt bò", "牛肉饭。", "Cơm thịt bò."),
    ("鸡肉", "jīròu", "thịt gà", "鸡肉好吃。", "Thịt gà ngon."),
    ("汤", "tāng", "canh", "喝汤。", "Uống canh."),
    ("酱油", "jiàngyóu", "nước tương", "加酱油。", "Thêm nước tương."),
    ("醋", "cù", "giấm", "加点醋。", "Thêm chút giấm."),
    ("油", "yóu", "dầu", "食用油。", "Dầu ăn."),
    ("味道", "wèidào", "mùi vị", "味道好。", "Vị ngon."),
    ("饺", "jiǎo", "sủi cảo", "包饺。", "Gói sủi cảo."),

    # ─── Cảm xúc & nội tâm ─────────────────────────
    ("情绪", "qíngxù", "cảm xúc", "情绪不好。", "Tâm trạng không tốt."),
    ("心情", "xīnqíng", "tâm trạng", "心情好。", "Tâm trạng tốt."),
    ("感情", "gǎnqíng", "tình cảm", "深厚感情。", "Tình cảm sâu sắc."),
    ("爱情", "àiqíng", "tình yêu", "美好的爱情。", "Tình yêu đẹp."),
    ("友情", "yǒuqíng", "tình bạn", "珍贵的友情。", "Tình bạn quý."),
    ("亲情", "qīnqíng", "tình thân", "亲情温暖。", "Tình thân ấm áp."),
    ("态度", "tàidu", "thái độ", "态度认真。", "Thái độ nghiêm túc."),
    ("性格", "xìnggé", "tính cách", "性格开朗。", "Tính cách cởi mở."),
    ("脾气", "píqi", "tính khí", "脾气不好。", "Tính tình không tốt."),
    ("印象", "yìnxiàng", "ấn tượng", "印象深刻。", "Ấn tượng sâu sắc."),
    ("梦想", "mèngxiǎng", "ước mơ", "实现梦想。", "Thực hiện ước mơ."),
    ("希望", "xīwàng", "hy vọng", "充满希望。", "Tràn đầy hy vọng."),
    ("失望", "shīwàng", "thất vọng", "我很失望。", "Tôi rất thất vọng."),
    ("绝望", "juéwàng", "tuyệt vọng", "感到绝望。", "Cảm thấy tuyệt vọng."),
    ("孤独", "gūdú", "cô độc", "孤独的夜。", "Đêm cô độc."),
    ("寂寞", "jìmò", "cô đơn", "感到寂寞。", "Cảm thấy cô đơn."),
    ("羡慕", "xiànmù", "ngưỡng mộ", "羡慕你。", "Ngưỡng mộ bạn."),
    ("嫉妒", "jídù", "ghen tị", "嫉妒别人。", "Ghen tị với người khác."),
    ("惊讶", "jīngyà", "ngạc nhiên", "我很惊讶。", "Tôi rất ngạc nhiên."),
    ("吃惊", "chījīng", "kinh ngạc", "他很吃惊。", "Anh ấy kinh ngạc."),
    ("害怕", "hàipà", "sợ hãi", "我害怕黑暗。", "Tôi sợ bóng tối."),
    ("恐怕", "kǒngpà", "e rằng", "恐怕来不了。", "E rằng không đến được."),

    # ─── Học thuật & nghề nghiệp ───────────────────
    ("文学", "wénxué", "văn học", "中国文学。", "Văn học TQ."),
    ("艺术", "yìshù", "nghệ thuật", "艺术作品。", "Tác phẩm nghệ thuật."),
    ("科学", "kēxué", "khoa học", "科学研究。", "Nghiên cứu KH."),
    ("技术", "jìshù", "kỹ thuật", "高技术。", "Kỹ thuật cao."),
    ("数学", "shùxué", "toán học", "数学题。", "Bài toán."),
    ("物理", "wùlǐ", "vật lý", "物理课。", "Tiết vật lý."),
    ("化学", "huàxué", "hoá học", "化学实验。", "Thí nghiệm hoá."),
    ("地理", "dìlǐ", "địa lý", "学地理。", "Học địa lý."),
    ("教育", "jiàoyù", "giáo dục", "教育孩子。", "Giáo dục trẻ."),
    ("学历", "xuélì", "học vị", "高学历。", "Học vị cao."),
    ("学问", "xuéwèn", "học vấn", "有学问。", "Có học vấn."),
    ("专业", "zhuānyè", "chuyên ngành", "我的专业。", "Chuyên ngành của tôi."),
    ("研究", "yánjiū", "nghiên cứu", "研究问题。", "Nghiên cứu vấn đề."),
    ("调查", "diàochá", "điều tra", "市场调查。", "Điều tra thị trường."),
    ("结果", "jiéguǒ", "kết quả", "考试结果。", "Kết quả thi."),
    ("效果", "xiàoguǒ", "hiệu quả", "效果好。", "Hiệu quả tốt."),
    ("基础", "jīchǔ", "nền tảng", "基础好。", "Nền tảng tốt."),
    ("内容", "nèiróng", "nội dung", "课文内容。", "Nội dung bài."),
    ("形式", "xíngshì", "hình thức", "新形式。", "Hình thức mới."),
    ("方面", "fāngmiàn", "mặt, phương diện", "各方面。", "Các mặt."),
    ("过程", "guòchéng", "quá trình", "学习过程。", "Quá trình học."),
    ("阶段", "jiēduàn", "giai đoạn", "新阶段。", "Giai đoạn mới."),
    ("条件", "tiáojiàn", "điều kiện", "工作条件。", "Điều kiện làm việc."),
    ("情况", "qíngkuàng", "tình hình", "情况怎么样？", "Tình hình thế nào?"),
    ("现象", "xiànxiàng", "hiện tượng", "社会现象。", "Hiện tượng XH."),
    ("原因", "yuányīn", "nguyên nhân", "找原因。", "Tìm nguyên nhân."),
    ("理由", "lǐyóu", "lý do", "什么理由？", "Lý do gì?"),
    ("目的", "mùdì", "mục đích", "学习目的。", "Mục đích học."),
    ("目标", "mùbiāo", "mục tiêu", "实现目标。", "Đạt mục tiêu."),
    ("意义", "yìyì", "ý nghĩa", "重要意义。", "Ý nghĩa quan trọng."),
    ("作用", "zuòyòng", "tác dụng", "起作用。", "Có tác dụng."),
    ("功能", "gōngnéng", "chức năng", "新功能。", "Chức năng mới."),
    ("特点", "tèdiǎn", "đặc điểm", "主要特点。", "Đặc điểm chính."),
    ("优点", "yōudiǎn", "ưu điểm", "他的优点。", "Ưu điểm của anh ấy."),
    ("缺点", "quēdiǎn", "khuyết điểm", "缺点很少。", "Khuyết điểm ít."),
    ("观点", "guāndiǎn", "quan điểm", "我的观点。", "Quan điểm của tôi."),
    ("看法", "kànfǎ", "cách nhìn", "你的看法？", "Cách nhìn của bạn?"),
    ("想法", "xiǎngfǎ", "suy nghĩ", "好想法。", "Ý hay."),
    ("意见", "yìjiàn", "ý kiến", "提意见。", "Đưa ý kiến."),
    ("印", "yìn", "in, dấu", "印名片。", "In danh thiếp."),
    ("作家", "zuòjiā", "nhà văn", "有名的作家。", "Nhà văn nổi tiếng."),
    ("画家", "huàjiā", "hoạ sĩ", "著名画家。", "Hoạ sĩ nổi tiếng."),
    ("演员", "yǎnyuán", "diễn viên", "有名的演员。", "Diễn viên nổi tiếng."),
    ("歌手", "gēshǒu", "ca sĩ", "新歌手。", "Ca sĩ mới."),
    ("记者", "jìzhě", "phóng viên", "电视记者。", "Phóng viên TV."),
    ("律师", "lǜshī", "luật sư", "聘请律师。", "Mời luật sư."),
    ("警察", "jǐngchá", "cảnh sát", "找警察。", "Tìm cảnh sát."),
    ("司机", "sījī", "tài xế", "出租车司机。", "Tài xế taxi."),
    ("护士", "hùshi", "y tá", "好护士。", "Y tá tốt."),
    ("教授", "jiàoshòu", "giáo sư", "大学教授。", "Giáo sư đại học."),
    ("博士", "bóshì", "tiến sĩ", "博士学位。", "Học vị tiến sĩ."),
    ("硕士", "shuòshì", "thạc sĩ", "硕士学位。", "Học vị thạc sĩ."),
    ("员工", "yuángōng", "nhân viên", "公司员工。", "Nhân viên công ty."),
    ("顾客", "gùkè", "khách hàng", "服务顾客。", "Phục vụ khách hàng."),
    ("客户", "kèhù", "khách hàng (BB)", "重要客户。", "Khách hàng quan trọng."),
    ("市民", "shìmín", "thị dân", "市民生活。", "Cuộc sống thị dân."),
    ("农民", "nóngmín", "nông dân", "农民种地。", "Nông dân trồng trọt."),

    # ─── Tài chính & mua sắm ───────────────────────
    ("收入", "shōurù", "thu nhập", "高收入。", "Thu nhập cao."),
    ("工资", "gōngzī", "tiền lương", "发工资。", "Phát lương."),
    ("奖金", "jiǎngjīn", "tiền thưởng", "年终奖金。", "Thưởng cuối năm."),
    ("税", "shuì", "thuế", "交税。", "Đóng thuế."),
    ("现金", "xiànjīn", "tiền mặt", "用现金。", "Dùng tiền mặt."),
    ("账号", "zhànghào", "số tài khoản", "银行账号。", "Tài khoản NH."),
    ("密码", "mìmǎ", "mật khẩu", "忘了密码。", "Quên mật khẩu."),
    ("支票", "zhīpiào", "séc, chi phiếu", "开支票。", "Phát hành séc."),
    ("存", "cún", "gửi (tiền), lưu", "存钱。", "Gửi tiền."),
    ("取", "qǔ", "rút (tiền), lấy", "取钱。", "Rút tiền."),
    ("贷款", "dàikuǎn", "vay tiền", "申请贷款。", "Xin vay."),
    ("利息", "lìxī", "lãi suất", "高利息。", "Lãi cao."),
    ("发票", "fāpiào", "hoá đơn", "开发票。", "Xuất hoá đơn."),
    ("零钱", "língqián", "tiền lẻ", "找零钱。", "Trả lại tiền lẻ."),
    ("价格", "jiàgé", "giá cả", "价格合理。", "Giá hợp lý."),
    ("价值", "jiàzhí", "giá trị", "有价值。", "Có giá trị."),
    ("浪费", "làngfèi", "lãng phí", "浪费时间。", "Lãng phí thời gian."),
    ("节约", "jiéyuē", "tiết kiệm", "节约能源。", "Tiết kiệm NL."),
    ("节省", "jiéshěng", "tiết kiệm", "节省时间。", "Tiết kiệm TG."),
    ("免费", "miǎnfèi", "miễn phí", "免费服务。", "DV miễn phí."),
    ("收费", "shōufèi", "thu phí", "停车收费。", "Đỗ xe thu phí."),

    # ─── Y tế & sức khoẻ ───────────────────────────
    ("血", "xiě", "máu", "出血了。", "Chảy máu rồi."),
    ("呼吸", "hūxī", "hô hấp", "深呼吸。", "Hít sâu."),
    ("心脏", "xīnzàng", "tim", "心脏病。", "Bệnh tim."),
    ("感染", "gǎnrǎn", "nhiễm trùng", "细菌感染。", "Nhiễm khuẩn."),
    ("打针", "dǎzhēn", "tiêm", "去打针。", "Đi tiêm."),
    ("住院", "zhùyuàn", "nhập viện", "他住院了。", "Anh ấy nhập viện."),
    ("出院", "chūyuàn", "xuất viện", "明天出院。", "Mai xuất viện."),
    ("医学", "yīxué", "y học", "学医学。", "Học y học."),
    ("药品", "yàopǐn", "thuốc men", "进口药品。", "Thuốc nhập."),
    ("营养", "yíngyǎng", "dinh dưỡng", "营养丰富。", "Dinh dưỡng phong phú."),
    ("健身", "jiànshēn", "tập thể dục", "去健身房。", "Đi phòng tập."),
    ("瑜伽", "yújiā", "yoga", "练瑜伽。", "Tập yoga."),

    # ─── Phương tiện & du lịch ─────────────────────
    ("交通", "jiāotōng", "giao thông", "交通堵塞。", "Tắc đường."),
    ("堵车", "dǔchē", "tắc đường", "今天堵车。", "Hôm nay tắc đường."),
    ("加油站", "jiāyóuzhàn", "trạm xăng", "去加油站。", "Đi trạm xăng."),
    ("停车场", "tíngchēchǎng", "bãi đỗ xe", "停车场满了。", "Bãi đỗ đầy."),
    ("机票", "jīpiào", "vé máy bay", "买机票。", "Mua vé máy bay."),
    ("护照", "hùzhào", "hộ chiếu", "申请护照。", "Xin hộ chiếu."),
    ("签证", "qiānzhèng", "visa", "办签证。", "Làm visa."),
    ("行程", "xíngchéng", "lịch trình", "旅行行程。", "Lịch trình du lịch."),
    ("登机", "dēngjī", "lên máy bay", "登机时间。", "Giờ lên máy bay."),
    ("降落", "jiàngluò", "hạ cánh", "飞机降落。", "Máy bay hạ cánh."),
    ("旅行社", "lǚxíngshè", "công ty du lịch", "通过旅行社。", "Qua công ty du lịch."),
    ("景点", "jǐngdiǎn", "điểm tham quan", "著名景点。", "Điểm nổi tiếng."),

    # ─── Công nghệ ─────────────────────────────────
    ("互联网", "hùliánwǎng", "internet", "上互联网。", "Lên mạng."),
    ("网络", "wǎngluò", "mạng", "网络速度。", "Tốc độ mạng."),
    ("网站", "wǎngzhàn", "trang web", "公司网站。", "Trang công ty."),
    ("软件", "ruǎnjiàn", "phần mềm", "下载软件。", "Tải phần mềm."),
    ("硬件", "yìngjiàn", "phần cứng", "电脑硬件。", "Phần cứng máy tính."),
    ("文件", "wénjiàn", "tệp tin", "保存文件。", "Lưu tệp."),
    ("数据", "shùjù", "dữ liệu", "数据分析。", "Phân tích DL."),
    ("信息", "xìnxī", "thông tin", "重要信息。", "TT quan trọng."),
    ("消息", "xiāoxi", "tin tức", "好消息。", "Tin tốt."),
    ("打印机", "dǎyìnjī", "máy in", "用打印机。", "Dùng máy in."),
    ("键盘", "jiànpán", "bàn phím", "新键盘。", "Bàn phím mới."),
    ("鼠标", "shǔbiāo", "chuột máy tính", "无线鼠标。", "Chuột không dây."),
    ("屏幕", "píngmù", "màn hình", "大屏幕。", "Màn hình lớn."),
    ("耳机", "ěrjī", "tai nghe", "戴耳机。", "Đeo tai nghe."),
    ("充电", "chōngdiàn", "sạc điện", "手机充电。", "Sạc điện thoại."),
    ("信号", "xìnhào", "tín hiệu", "信号弱。", "Tín hiệu yếu."),
    ("应用", "yìngyòng", "ứng dụng", "下载应用。", "Tải ứng dụng."),
    ("登录", "dēnglù", "đăng nhập", "登录账号。", "Đăng nhập tài khoản."),
    ("注册", "zhùcè", "đăng ký", "注册账号。", "Đăng ký tài khoản."),
    ("密码", "mìmǎ", "mật khẩu", "设置密码。", "Đặt mật khẩu."),

    # ─── Liên từ, giới từ nâng cao ────────────────
    ("尽管", "jǐnguǎn", "mặc dù", "尽管累还坚持。", "Mặc dù mệt vẫn kiên trì."),
    ("不过", "búguò", "tuy nhiên", "我累，不过开心。", "Tôi mệt, tuy nhiên vui."),
    ("无论", "wúlùn", "bất kể", "无论如何。", "Bất luận thế nào."),
    ("不管", "bùguǎn", "bất kể", "不管多远。", "Bất kể bao xa."),
    ("即使", "jíshǐ", "dù cho", "即使下雨也去。", "Dù mưa cũng đi."),
    ("凡是", "fánshì", "phàm là", "凡是来的。", "Phàm là người đến."),
    ("除了", "chúle", "ngoài ra", "除了他都来了。", "Ngoài anh ấy đều đến."),
    ("此外", "cǐwài", "ngoài ra", "此外还有。", "Ngoài ra còn có."),
    ("另外", "lìngwài", "khác, ngoài ra", "另外的事。", "Việc khác."),
    ("其余", "qíyú", "còn lại", "其余的人。", "Những người còn lại."),
    ("此", "cǐ", "này", "由此可见。", "Có thể thấy."),
    ("由于", "yóuyú", "do, bởi vì", "由于天气。", "Do thời tiết."),
    ("既然", "jìrán", "đã, vì", "既然来了就坐。", "Đã đến thì ngồi."),
    ("因此", "yīncǐ", "vì vậy", "因此决定。", "Vì vậy quyết định."),
    ("总之", "zǒngzhī", "tóm lại", "总之很好。", "Tóm lại rất tốt."),
    ("总的来说", "zǒngdeláishuō", "nói chung", "总的来说不错。", "Nói chung khá tốt."),
    ("反正", "fǎnzhèng", "đằng nào cũng", "反正要去。", "Đằng nào cũng đi."),
    ("也许", "yěxǔ", "có lẽ", "也许明天。", "Có lẽ ngày mai."),
    ("或许", "huòxǔ", "có thể", "或许可以。", "Có thể được."),
    ("万一", "wànyī", "vạn nhất", "万一下雨。", "Lỡ trời mưa."),
    ("难道", "nándào", "lẽ nào", "难道你不知道？", "Lẽ nào bạn không biết?"),
    ("竟然", "jìngrán", "chẳng ngờ", "竟然成功了。", "Không ngờ thành công."),
    ("居然", "jūrán", "không ngờ", "居然忘了。", "Không ngờ quên."),
    ("幸亏", "xìngkuī", "may mà", "幸亏带了伞。", "May mà mang ô."),
    ("既", "jì", "đã", "既然如此。", "Đã như vậy."),
    ("并", "bìng", "và, hơn nữa", "并不是。", "Không phải."),
    ("并且", "bìngqiě", "và, hơn nữa", "好吃并且便宜。", "Ngon và rẻ."),
    ("不仅", "bùjǐn", "không chỉ", "不仅聪明。", "Không chỉ thông minh."),
    ("不光", "bùguāng", "không chỉ", "不光我。", "Không chỉ tôi."),
    ("反而", "fǎn'ér", "ngược lại", "反而更难。", "Ngược lại càng khó."),
    ("到底", "dàodǐ", "rốt cuộc", "到底是谁？", "Rốt cuộc là ai?"),

    # ─── Phẩm chất, đánh giá ───────────────────────
    ("漂亮", "piàoliang", "xinh đẹp", "漂亮的衣服。", "Quần áo đẹp."),
    ("高级", "gāojí", "cao cấp", "高级餐厅。", "Nhà hàng cao cấp."),
    ("低级", "dījí", "thấp cấp", "低级错误。", "Lỗi sơ đẳng."),
    ("中级", "zhōngjí", "trung cấp", "中级水平。", "Trình độ trung cấp."),
    ("高速", "gāosù", "tốc độ cao", "高速公路。", "Đường cao tốc."),
    ("低", "dī", "thấp", "声音低。", "Tiếng thấp."),
    ("强", "qiáng", "mạnh", "身体强。", "Cơ thể khoẻ."),
    ("弱", "ruò", "yếu", "身体弱。", "Cơ thể yếu."),
    ("厚", "hòu", "dày", "厚书。", "Sách dày."),
    ("薄", "báo", "mỏng", "薄纸。", "Giấy mỏng."),
    ("圆", "yuán", "tròn", "圆桌。", "Bàn tròn."),
    ("方", "fāng", "vuông", "方桌。", "Bàn vuông."),
    ("尖", "jiān", "nhọn", "尖刀。", "Dao nhọn."),
    ("深", "shēn", "sâu", "海很深。", "Biển sâu."),
    ("浅", "qiǎn", "nông, nhạt", "水很浅。", "Nước nông."),
    ("宽", "kuān", "rộng", "路宽。", "Đường rộng."),
    ("窄", "zhǎi", "hẹp", "路窄。", "Đường hẹp."),

    # ─── Hành chính & văn bản ──────────────────────
    ("身份证", "shēnfènzhèng", "chứng minh thư", "出示身份证。", "Xuất trình CMT."),
    ("证件", "zhèngjiàn", "giấy tờ", "带证件。", "Mang giấy tờ."),
    ("合同", "hétóng", "hợp đồng", "签合同。", "Ký HĐ."),
    ("协议", "xiéyì", "thoả thuận", "达成协议。", "Đạt thoả thuận."),
    ("文章", "wénzhāng", "bài viết", "写文章。", "Viết bài."),
    ("报告", "bàogào", "báo cáo", "写报告。", "Viết báo cáo."),
    ("通知", "tōngzhī", "thông báo", "发通知。", "Phát thông báo."),
    ("广告", "guǎnggào", "quảng cáo", "看广告。", "Xem quảng cáo."),
    ("杂志", "zázhì", "tạp chí", "买杂志。", "Mua tạp chí."),
    ("报纸", "bàozhǐ", "báo giấy", "看报纸。", "Đọc báo."),
    ("小说", "xiǎoshuō", "tiểu thuyết", "写小说。", "Viết tiểu thuyết."),
    ("诗", "shī", "bài thơ", "写诗。", "Làm thơ."),
    ("章节", "zhāngjié", "chương, mục", "第一章节。", "Chương đầu."),
    ("题目", "tímù", "đề bài, tiêu đề", "题目难。", "Đề khó."),

    # ─── Sự kiện & hoạt động ───────────────────────
    ("活动", "huódòng", "hoạt động", "参加活动。", "Tham gia HĐ."),
    ("聚会", "jùhuì", "tụ họp", "朋友聚会。", "Họp mặt bạn bè."),
    ("派对", "pàiduì", "tiệc party", "举办派对。", "Tổ chức tiệc."),
    ("仪式", "yíshì", "nghi lễ", "开学仪式。", "Lễ khai giảng."),
    ("典礼", "diǎnlǐ", "buổi lễ", "毕业典礼。", "Lễ tốt nghiệp."),
    ("节日", "jiérì", "lễ tết", "国庆节日。", "Lễ Quốc khánh."),
    ("春节", "Chūnjié", "Tết Nguyên đán", "过春节。", "Đón Tết."),
    ("中秋节", "Zhōngqiūjié", "Tết Trung thu", "中秋节快乐。", "Trung thu vui vẻ."),
    ("假期", "jiàqī", "kỳ nghỉ", "暑假假期。", "Kỳ nghỉ hè."),
    ("假日", "jiàrì", "ngày nghỉ", "公共假日。", "Ngày nghỉ chung."),
    ("休假", "xiūjià", "nghỉ phép", "请休假。", "Xin nghỉ phép."),
    ("出差", "chūchāi", "đi công tác", "去北京出差。", "Đi công tác BK."),

    # ─── Khác ──────────────────────────────────────
    ("能源", "néngyuán", "năng lượng", "节约能源。", "Tiết kiệm NL."),
    ("功能", "gōngnéng", "chức năng", "这个功能。", "Chức năng này."),
    ("性质", "xìngzhì", "tính chất", "事物性质。", "Tính chất sự vật."),
    ("范围", "fànwéi", "phạm vi", "范围广。", "Phạm vi rộng."),
    ("程度", "chéngdù", "mức độ", "程度高。", "Mức độ cao."),
    ("数量", "shùliàng", "số lượng", "数量多。", "Số lượng nhiều."),
    ("质量", "zhìliàng", "chất lượng", "高质量。", "Chất lượng cao."),
    ("速度", "sùdù", "tốc độ", "高速度。", "Tốc độ cao."),
    ("距离", "jùlí", "khoảng cách", "保持距离。", "Giữ khoảng cách."),
    ("方向", "fāngxiàng", "phương hướng", "正确方向。", "Hướng đúng."),
    ("位置", "wèizhi", "vị trí", "好位置。", "Vị trí tốt."),
    ("地位", "dìwèi", "địa vị", "社会地位。", "Địa vị XH."),
    ("高度", "gāodù", "độ cao", "高度警惕。", "Cảnh giác cao độ."),
    ("长度", "chángdù", "chiều dài", "测量长度。", "Đo chiều dài."),
    ("尺寸", "chǐcùn", "kích thước", "标准尺寸。", "Kích thước chuẩn."),
    ("重量", "zhòngliàng", "trọng lượng", "重量轻。", "Trọng lượng nhẹ."),
    ("体重", "tǐzhòng", "cân nặng", "体重增加。", "Cân nặng tăng."),
    ("身高", "shēngāo", "chiều cao", "身高一米七。", "Cao 1m7."),
    ("年龄", "niánlíng", "tuổi tác", "年龄不大。", "Tuổi không lớn."),
    ("性别", "xìngbié", "giới tính", "性别男。", "Giới tính nam."),
    ("国籍", "guójí", "quốc tịch", "中国国籍。", "Quốc tịch TQ."),
    ("语言", "yǔyán", "ngôn ngữ", "外国语言。", "Ngoại ngữ."),
    ("方言", "fāngyán", "tiếng địa phương", "上海方言。", "Tiếng Thượng Hải."),
    ("世纪", "shìjì", "thế kỷ", "二十一世纪。", "Thế kỷ 21."),
    ("组织", "zǔzhī", "tổ chức", "国际组织。", "Tổ chức quốc tế."),
    ("团体", "tuántǐ", "tập thể", "团体活动。", "HĐ tập thể."),
    ("队伍", "duìwǔ", "đội ngũ", "队伍整齐。", "Đội ngũ chỉnh tề."),
    ("成员", "chéngyuán", "thành viên", "团队成员。", "Thành viên đội."),
    ("领导", "lǐngdǎo", "lãnh đạo", "公司领导。", "Lãnh đạo công ty."),
    ("管理", "guǎnlǐ", "quản lý", "管理公司。", "Quản lý công ty."),
    ("负责", "fùzé", "phụ trách", "负责项目。", "Phụ trách dự án."),
    ("责任", "zérèn", "trách nhiệm", "有责任。", "Có trách nhiệm."),
    ("义务", "yìwù", "nghĩa vụ", "公民义务。", "Nghĩa vụ công dân."),
    ("权利", "quánlì", "quyền lợi", "保护权利。", "Bảo vệ quyền lợi."),
    ("权力", "quánlì", "quyền lực", "国家权力。", "Quyền lực nhà nước."),
    ("自由", "zìyóu", "tự do", "言论自由。", "Tự do ngôn luận."),
    ("民主", "mínzhǔ", "dân chủ", "民主国家。", "Nước dân chủ."),
    ("平等", "píngděng", "bình đẳng", "男女平等。", "Bình đẳng nam nữ."),
    ("正义", "zhèngyì", "chính nghĩa", "正义之战。", "Chiến tranh chính nghĩa."),
    ("关键", "guānjiàn", "then chốt", "关键问题。", "Vấn đề then chốt."),
    ("重点", "zhòngdiǎn", "trọng điểm", "工作重点。", "Trọng điểm công việc."),
    ("主要", "zhǔyào", "chủ yếu", "主要原因。", "Nguyên nhân chính."),
    ("次要", "cìyào", "thứ yếu", "次要问题。", "Vấn đề phụ."),
    ("基本", "jīběn", "cơ bản", "基本完成。", "Cơ bản hoàn thành."),
    ("根本", "gēnběn", "cơ bản, gốc", "根本不行。", "Hoàn toàn không được."),
    ("彻底", "chèdǐ", "triệt để", "彻底解决。", "Giải quyết triệt để."),
    ("完全", "wánquán", "hoàn toàn", "完全同意。", "Hoàn toàn đồng ý."),
    ("绝对", "juéduì", "tuyệt đối", "绝对正确。", "Hoàn toàn đúng."),
    ("相对", "xiāngduì", "tương đối", "相对容易。", "Tương đối dễ."),
    ("永久", "yǒngjiǔ", "vĩnh viễn", "永久居留。", "Cư trú vĩnh viễn."),
    ("临时", "línshí", "tạm thời", "临时工作。", "Công việc tạm."),
    ("正常", "zhèngcháng", "bình thường", "一切正常。", "Mọi thứ bình thường."),
    ("异常", "yìcháng", "bất thường", "情况异常。", "Tình hình bất thường."),
    ("具体", "jùtǐ", "cụ thể", "具体计划。", "Kế hoạch cụ thể."),
    ("抽象", "chōuxiàng", "trừu tượng", "抽象概念。", "Khái niệm trừu tượng."),
    ("理论", "lǐlùn", "lý thuyết", "学习理论。", "Học lý thuyết."),
    ("实际", "shíjì", "thực tế", "实际情况。", "Tình hình thực tế."),
    ("实践", "shíjiàn", "thực tiễn", "实践经验。", "Kinh nghiệm thực tiễn."),
    ("经验", "jīngyàn", "kinh nghiệm", "工作经验。", "Kinh nghiệm làm việc."),
    ("教训", "jiàoxun", "bài học", "吸取教训。", "Rút ra bài học."),
    ("印象", "yìnxiàng", "ấn tượng", "好印象。", "Ấn tượng tốt."),
    ("记忆", "jìyì", "ký ức", "美好的记忆。", "Ký ức đẹp."),
    ("回忆", "huíyì", "hồi tưởng", "回忆过去。", "Hồi tưởng quá khứ."),
    ("梦想", "mèngxiǎng", "mơ ước", "实现梦想。", "Thực hiện ước mơ."),
    ("理想", "lǐxiǎng", "lý tưởng", "崇高理想。", "Lý tưởng cao."),
    ("现实", "xiànshí", "hiện thực", "面对现实。", "Đối mặt thực tế."),
    ("未来", "wèilái", "tương lai", "美好未来。", "Tương lai đẹp."),
    ("信心", "xìnxīn", "tự tin, niềm tin", "充满信心。", "Tràn đầy tự tin."),
    ("信仰", "xìnyǎng", "tín ngưỡng", "宗教信仰。", "Tín ngưỡng tôn giáo."),
    ("宗教", "zōngjiào", "tôn giáo", "宗教自由。", "Tự do tôn giáo."),
    ("传统", "chuántǒng", "truyền thống", "传统文化。", "Văn hoá truyền thống."),
    ("现代", "xiàndài", "hiện đại", "现代生活。", "Cuộc sống hiện đại."),
    ("古代", "gǔdài", "cổ đại", "古代历史。", "Lịch sử cổ đại."),
    ("古典", "gǔdiǎn", "cổ điển", "古典音乐。", "Nhạc cổ điển."),
    ("国际", "guójì", "quốc tế", "国际会议。", "Hội nghị quốc tế."),
    ("国内", "guónèi", "trong nước", "国内市场。", "Thị trường trong nước."),
    ("国外", "guówài", "nước ngoài", "去国外。", "Ra nước ngoài."),
    ("外国", "wàiguó", "nước ngoài", "外国人。", "Người nước ngoài."),
    ("华人", "huárén", "người Hoa", "海外华人。", "Người Hoa hải ngoại."),

    # ─── Bổ sung thêm ──────────────────────────────
    ("打扰", "dǎrǎo", "làm phiền", "打扰你了。", "Làm phiền bạn rồi."),
    ("麻烦", "máfan", "phiền phức", "麻烦你了。", "Làm phiền bạn rồi."),
    ("辛苦", "xīnkǔ", "vất vả", "辛苦了。", "Vất vả rồi."),
    ("祝贺", "zhùhè", "chúc mừng", "祝贺你成功。", "Chúc mừng bạn."),
    ("庆祝", "qìngzhù", "ăn mừng", "庆祝生日。", "Mừng sinh nhật."),
    ("享受", "xiǎngshòu", "tận hưởng", "享受生活。", "Tận hưởng cuộc sống."),
    ("欣赏", "xīnshǎng", "thưởng thức", "欣赏音乐。", "Thưởng thức âm nhạc."),
    ("珍惜", "zhēnxī", "trân trọng", "珍惜时间。", "Trân trọng thời gian."),
    ("回顾", "huígù", "nhìn lại", "回顾过去一年。", "Nhìn lại năm qua."),
    ("展望", "zhǎnwàng", "triển vọng, nhìn về", "展望未来。", "Nhìn về tương lai."),
    ("观察", "guānchá", "quan sát", "仔细观察。", "Quan sát kỹ."),
    ("观看", "guānkàn", "xem", "观看比赛。", "Xem trận đấu."),
    ("展开", "zhǎnkāi", "mở rộng, triển khai", "展开讨论。", "Mở thảo luận."),
    ("展览", "zhǎnlǎn", "triển lãm", "艺术展览。", "Triển lãm NT."),
    ("说服", "shuōfú", "thuyết phục", "说服他。", "Thuyết phục anh ấy."),
    ("劝", "quàn", "khuyên", "劝你别去。", "Khuyên bạn đừng đi."),
    ("命令", "mìnglìng", "mệnh lệnh", "下命令。", "Ra lệnh."),
    ("要求", "yāoqiú", "yêu cầu", "提出要求。", "Đưa yêu cầu."),
    ("请求", "qǐngqiú", "thỉnh cầu", "请求帮助。", "Cầu xin giúp đỡ."),
    ("询问", "xúnwèn", "hỏi thăm", "询问情况。", "Hỏi tình hình."),
    ("征求", "zhēngqiú", "trưng cầu", "征求意见。", "Trưng cầu ý kiến."),
    ("通过", "tōngguò", "thông qua", "通过考试。", "Vượt qua kỳ thi."),
    ("经过", "jīngguò", "trải qua", "经过努力。", "Trải qua nỗ lực."),
    ("绕", "rào", "vòng quanh", "绕一圈。", "Đi vòng một vòng."),
    ("追", "zhuī", "đuổi theo", "追梦。", "Đuổi theo ước mơ."),
    ("赶", "gǎn", "đuổi, kịp", "赶时间。", "Kịp thời gian."),
    ("飞", "fēi", "bay", "鸟在飞。", "Chim bay."),
    ("跳", "tiào", "nhảy", "跳起来。", "Nhảy lên."),
    ("爬", "pá", "leo, bò", "爬山。", "Leo núi."),
    ("游", "yóu", "bơi, chu du", "游泳。", "Bơi."),
    ("赞美", "zànměi", "tán dương", "赞美她。", "Khen ngợi cô ấy."),
    ("称赞", "chēngzàn", "khen ngợi", "称赞孩子。", "Khen trẻ."),
    ("夸", "kuā", "khen", "夸她漂亮。", "Khen cô ấy đẹp."),
    ("发愁", "fāchóu", "lo buồn", "发愁工作。", "Lo về công việc."),
    ("操心", "cāoxīn", "lo lắng", "为孩子操心。", "Lo cho con."),
    ("烦恼", "fánnǎo", "phiền não", "工作烦恼。", "Phiền não công việc."),
    ("难受", "nánshòu", "khó chịu", "心里难受。", "Trong lòng khó chịu."),
    ("愉快", "yúkuài", "vui vẻ", "愉快的旅行。", "Chuyến đi vui."),
    ("开心", "kāixīn", "vui", "今天很开心。", "Hôm nay rất vui."),
    ("兴奋", "xīngfèn", "phấn khích", "我很兴奋。", "Tôi rất phấn khích."),
    ("吃醋", "chīcù", "ghen", "她吃醋了。", "Cô ấy ghen rồi."),
    ("爱上", "ài shàng", "yêu", "爱上他。", "Yêu anh ấy."),
    ("分手", "fēnshǒu", "chia tay", "他们分手了。", "Họ chia tay rồi."),
    ("感动", "gǎndòng", "cảm động", "故事感动人。", "Câu chuyện cảm động."),
    ("惊讶", "jīngyà", "ngạc nhiên", "我感到惊讶。", "Tôi cảm thấy ngạc nhiên."),
    ("吓", "xià", "doạ, sợ", "吓我一跳。", "Doạ tôi giật mình."),
    ("讽刺", "fěngcì", "châm biếm", "讽刺人。", "Châm biếm người."),
    ("嘲笑", "cháoxiào", "chế giễu", "别嘲笑别人。", "Đừng chế giễu người."),
    ("乐观", "lèguān", "lạc quan", "保持乐观。", "Giữ lạc quan."),
    ("悲观", "bēiguān", "bi quan", "别悲观。", "Đừng bi quan."),
]

