# ~500 từ tiếng Trung về đời sống hằng ngày
# format: (hanzi, pinyin, meaning, example_zh, example_vn)

WORDS = [
    # ─── CHÀO HỎI & GIAO TIẾP ───────────────────────────────
    ("你好", "nǐ hǎo", "xin chào", "你好，很高兴认识你！", "Xin chào, rất vui được gặp bạn!"),
    ("再见", "zàijiàn", "tạm biệt", "明天见，再见！", "Hẹn gặp lại ngày mai, tạm biệt!"),
    ("谢谢", "xièxiè", "cảm ơn", "谢谢你的帮助。", "Cảm ơn sự giúp đỡ của bạn."),
    ("不客气", "bú kèqì", "không có gì / không khách sáo", "谢谢！不客气。", "Cảm ơn! Không có gì."),
    ("对不起", "duìbuqǐ", "xin lỗi", "对不起，我来晚了。", "Xin lỗi, tôi đến muộn."),
    ("没关系", "méi guānxi", "không sao", "没关系，没事的。", "Không sao, không có chuyện gì."),
    ("请问", "qǐngwèn", "xin hỏi", "请问，洗手间在哪里？", "Xin hỏi, nhà vệ sinh ở đâu?"),
    ("是的", "shìde", "vâng / đúng vậy", "是的，我是越南人。", "Vâng, tôi là người Việt Nam."),
    ("不是", "bú shì", "không phải", "不是，这不是我的。", "Không phải, đây không phải của tôi."),
    ("好的", "hǎo de", "được / okay", "好的，我明白了。", "Được rồi, tôi hiểu rồi."),
    ("我", "wǒ", "tôi", "我是学生。", "Tôi là học sinh."),
    ("你", "nǐ", "bạn / anh / chị", "你吃饭了吗？", "Bạn ăn cơm chưa?"),
    ("他", "tā", "anh ấy / ông ấy", "他是我的朋友。", "Anh ấy là bạn tôi."),
    ("她", "tā", "cô ấy / bà ấy", "她很聪明。", "Cô ấy rất thông minh."),
    ("我们", "wǒmen", "chúng tôi / chúng ta", "我们一起去吧。", "Chúng ta cùng đi nhé."),
    ("什么", "shénme", "cái gì / gì", "这是什么？", "Đây là cái gì?"),
    ("哪里", "nǎlǐ", "ở đâu", "你住在哪里？", "Bạn sống ở đâu?"),
    ("为什么", "wèishénme", "tại sao", "你为什么学习汉语？", "Tại sao bạn học tiếng Trung?"),
    ("怎么", "zěnme", "như thế nào / làm sao", "你好吗？ 怎么了？", "Bạn có khỏe không? Có chuyện gì vậy?"),
    ("多少", "duōshǎo", "bao nhiêu", "这个多少钱？", "Cái này bao nhiêu tiền?"),
    ("现在", "xiànzài", "bây giờ / hiện tại", "现在几点了？", "Bây giờ là mấy giờ rồi?"),
    ("一起", "yīqǐ", "cùng nhau", "我们一起学习吧。", "Chúng ta cùng học nhé."),
    ("知道", "zhīdào", "biết", "我不知道。", "Tôi không biết."),
    ("明白", "míngbái", "hiểu", "你明白了吗？", "Bạn hiểu chưa?"),
    ("可以", "kěyǐ", "có thể / được phép", "我可以进来吗？", "Tôi có thể vào không?"),

    # ─── GIA ĐÌNH ───────────────────────────────────────────
    ("家庭", "jiātíng", "gia đình", "我很爱我的家庭。", "Tôi rất yêu gia đình mình."),
    ("爸爸", "bàba", "bố / ba", "爸爸每天早起。", "Bố dậy sớm mỗi ngày."),
    ("妈妈", "māma", "mẹ", "妈妈做的饭很好吃。", "Cơm mẹ nấu rất ngon."),
    ("哥哥", "gēgē", "anh trai", "我哥哥比我大三岁。", "Anh trai tôi lớn hơn tôi 3 tuổi."),
    ("姐姐", "jiějie", "chị gái", "姐姐在大学读书。", "Chị gái học đại học."),
    ("弟弟", "dìdì", "em trai", "弟弟很调皮。", "Em trai rất nghịch ngợm."),
    ("妹妹", "mèimèi", "em gái", "妹妹喜欢画画。", "Em gái thích vẽ."),
    ("爷爷", "yéye", "ông nội", "爷爷每天散步。", "Ông nội đi bộ mỗi ngày."),
    ("奶奶", "nǎinai", "bà nội", "奶奶会做很多菜。", "Bà nội biết nấu nhiều món."),
    ("外公", "wàigōng", "ông ngoại", "外公喜欢钓鱼。", "Ông ngoại thích câu cá."),
    ("外婆", "wàipó", "bà ngoại", "外婆的故事很有趣。", "Những câu chuyện của bà ngoại rất thú vị."),
    ("丈夫", "zhàngfū", "chồng", "她的丈夫很体贴。", "Chồng cô ấy rất quan tâm."),
    ("妻子", "qīzi", "vợ", "他的妻子是医生。", "Vợ anh ấy là bác sĩ."),
    ("儿子", "érzi", "con trai", "儿子今年六岁。", "Con trai năm nay 6 tuổi."),
    ("女儿", "nǚ'ér", "con gái", "女儿很乖巧。", "Con gái rất ngoan ngoãn."),
    ("孩子", "háizi", "đứa trẻ / con cái", "孩子们在玩耍。", "Những đứa trẻ đang vui chơi."),
    ("叔叔", "shūshu", "chú (em trai bố)", "叔叔送给我礼物。", "Chú tặng quà cho tôi."),
    ("阿姨", "āyí", "cô / dì", "阿姨来我家做客。", "Cô đến nhà tôi thăm."),
    ("朋友", "péngyǒu", "bạn bè", "他是我最好的朋友。", "Anh ấy là bạn thân nhất của tôi."),
    ("邻居", "línjū", "hàng xóm", "邻居很友好。", "Hàng xóm rất thân thiện."),

    # ─── CƠ THỂ NGƯỜI ────────────────────────────────────────
    ("身体", "shēntǐ", "cơ thể / sức khỏe", "身体是最重要的。", "Sức khỏe là quan trọng nhất."),
    ("头", "tóu", "đầu", "我头很痛。", "Đầu tôi rất đau."),
    ("眼睛", "yǎnjing", "mắt", "她的眼睛很漂亮。", "Mắt cô ấy rất đẹp."),
    ("鼻子", "bízi", "mũi", "鼻子有点塞。", "Mũi hơi bị nghẹt."),
    ("嘴巴", "zuǐbā", "miệng", "嘴巴不舒服。", "Miệng không thoải mái."),
    ("耳朵", "ěrduǒ", "tai", "耳朵听得很清楚。", "Tai nghe rất rõ."),
    ("牙齿", "yáchǐ", "răng", "要好好刷牙齿。", "Phải đánh răng sạch sẽ."),
    ("头发", "tóufà", "tóc", "她的头发很长。", "Tóc cô ấy rất dài."),
    ("手", "shǒu", "tay / bàn tay", "洗手很重要。", "Rửa tay rất quan trọng."),
    ("脚", "jiǎo", "chân / bàn chân", "脚有点疼。", "Chân hơi đau."),
    ("腿", "tuǐ", "chân / đùi", "跑步后腿很累。", "Sau khi chạy bộ chân rất mỏi."),
    ("背", "bèi", "lưng", "背部有点酸。", "Lưng hơi mỏi."),
    ("心", "xīn", "tim / lòng", "心情很好。", "Tâm trạng rất tốt."),
    ("肚子", "dùzi", "bụng", "肚子饿了。", "Bụng đói rồi."),
    ("皮肤", "pífū", "da", "皮肤要注意保湿。", "Cần chú ý dưỡng ẩm cho da."),

    # ─── THỨC ĂN & ĐỒ UỐNG ──────────────────────────────────
    ("吃", "chī", "ăn", "你吃饭了吗？", "Bạn ăn cơm chưa?"),
    ("喝", "hē", "uống", "我想喝水。", "Tôi muốn uống nước."),
    ("饭", "fàn", "cơm / bữa ăn", "今天的饭很好吃。", "Bữa ăn hôm nay rất ngon."),
    ("米饭", "mǐfàn", "cơm trắng", "中国人喜欢吃米饭。", "Người Trung Quốc thích ăn cơm trắng."),
    ("面条", "miàntiáo", "mì sợi / phở", "我最爱吃面条。", "Tôi thích ăn mì nhất."),
    ("包子", "bāozi", "bánh bao", "早上我吃了两个包子。", "Sáng tôi ăn hai cái bánh bao."),
    ("饺子", "jiǎozi", "bánh sủi cảo", "过年要吃饺子。", "Tết phải ăn bánh sủi cảo."),
    ("面包", "miànbāo", "bánh mì", "我喜欢吃面包配黄油。", "Tôi thích ăn bánh mì với bơ."),
    ("鸡肉", "jīròu", "thịt gà", "这道菜用鸡肉做的。", "Món này làm từ thịt gà."),
    ("猪肉", "zhūròu", "thịt lợn / heo", "猪肉炒白菜很好吃。", "Thịt lợn xào bắp cải rất ngon."),
    ("牛肉", "niúròu", "thịt bò", "牛肉面很有名。", "Mì bò rất nổi tiếng."),
    ("鱼", "yú", "cá", "妈妈做了一道鱼。", "Mẹ nấu một món cá."),
    ("虾", "xiā", "tôm", "我喜欢吃虾。", "Tôi thích ăn tôm."),
    ("蔬菜", "shūcài", "rau củ", "多吃蔬菜对身体好。", "Ăn nhiều rau củ tốt cho sức khỏe."),
    ("水果", "shuǐguǒ", "trái cây / hoa quả", "每天吃水果很健康。", "Ăn trái cây mỗi ngày rất tốt."),
    ("苹果", "píngguǒ", "táo", "一天一苹果，医生远离我。", "Một quả táo mỗi ngày, bác sĩ tránh xa."),
    ("香蕉", "xiāngjiāo", "chuối", "香蕉有很多营养。", "Chuối có nhiều dinh dưỡng."),
    ("橙子", "chéngzi", "cam", "橙子富含维生素C。", "Cam giàu vitamin C."),
    ("西瓜", "xīguā", "dưa hấu", "夏天西瓜最好吃。", "Mùa hè dưa hấu ngon nhất."),
    ("葡萄", "pútáo", "nho", "这串葡萄很甜。", "Chùm nho này rất ngọt."),
    ("草莓", "cǎoméi", "dâu tây", "草莓蛋糕很好吃。", "Bánh dâu tây rất ngon."),
    ("鸡蛋", "jīdàn", "trứng gà", "早上我吃了一个鸡蛋。", "Sáng tôi ăn một quả trứng."),
    ("豆腐", "dòufu", "đậu phụ", "豆腐汤很清淡。", "Canh đậu phụ rất thanh đạm."),
    ("汤", "tāng", "canh / súp", "妈妈做了一锅汤。", "Mẹ nấu một nồi canh."),
    ("盐", "yán", "muối", "菜里盐放多了。", "Món ăn bị mặn quá."),
    ("糖", "táng", "đường / kẹo", "少吃糖对牙齿好。", "Ăn ít đường tốt cho răng."),
    ("油", "yóu", "dầu / dầu ăn", "炒菜要放油。", "Xào rau phải cho dầu vào."),
    ("酱油", "jiàngyóu", "nước tương / xì dầu", "红烧肉要加酱油。", "Thịt kho phải thêm xì dầu."),
    ("水", "shuǐ", "nước", "每天要多喝水。", "Mỗi ngày phải uống nhiều nước."),
    ("茶", "chá", "trà", "中国人爱喝茶。", "Người Trung Quốc thích uống trà."),
    ("咖啡", "kāfēi", "cà phê", "早上喝一杯咖啡。", "Buổi sáng uống một tách cà phê."),
    ("牛奶", "niúnǎi", "sữa bò", "每天早上喝牛奶。", "Mỗi sáng uống sữa bò."),
    ("果汁", "guǒzhī", "nước hoa quả", "我要一杯橙汁。", "Tôi muốn một ly nước cam."),
    ("啤酒", "píjiǔ", "bia", "朋友们一起喝啤酒。", "Bạn bè cùng uống bia."),
    ("饼干", "bǐnggān", "bánh quy", "我喜欢吃饼干。", "Tôi thích ăn bánh quy."),
    ("冰淇淋", "bīngqílín", "kem", "夏天吃冰淇淋很凉快。", "Mùa hè ăn kem rất mát."),
    ("巧克力", "qiǎokèlì", "sôcôla", "她喜欢吃巧克力。", "Cô ấy thích ăn sôcôla."),
    ("好吃", "hǎochī", "ngon", "这个菜真的很好吃！", "Món này thực sự rất ngon!"),
    ("难吃", "nán chī", "không ngon / dở", "这个味道有点难吃。", "Vị này hơi không ngon."),
    ("辣", "là", "cay", "川菜很辣。", "Món Tứ Xuyên rất cay."),
    ("甜", "tián", "ngọt", "这个蛋糕很甜。", "Chiếc bánh này rất ngọt."),
    ("咸", "xián", "mặn", "今天的菜有点咸。", "Món ăn hôm nay hơi mặn."),
    ("酸", "suān", "chua", "柠檬很酸。", "Chanh rất chua."),
    ("苦", "kǔ", "đắng", "这种药很苦。", "Loại thuốc này rất đắng."),
    ("饿", "è", "đói", "我很饿，想吃东西。", "Tôi rất đói, muốn ăn gì đó."),
    ("饱", "bǎo", "no", "我已经吃饱了。", "Tôi đã no rồi."),
    ("渴", "kě", "khát", "天气热，我很渴。", "Trời nóng, tôi rất khát."),
    ("餐厅", "cāntīng", "nhà hàng", "我们去餐厅吃饭吧。", "Chúng ta đến nhà hàng ăn nhé."),
    ("菜单", "càidān", "thực đơn", "请给我看菜单。", "Cho tôi xem thực đơn."),
    ("筷子", "kuàizi", "đũa", "中国人用筷子吃饭。", "Người Trung Quốc ăn bằng đũa."),

    # ─── ĐỘNG VẬT ────────────────────────────────────────────
    ("动物", "dòngwù", "động vật", "动物园里有很多动物。", "Sở thú có rất nhiều động vật."),
    ("狗", "gǒu", "chó", "他养了一只狗。", "Anh ấy nuôi một con chó."),
    ("猫", "māo", "mèo", "猫喜欢睡觉。", "Mèo thích ngủ."),
    ("鸟", "niǎo", "chim", "树上有一只鸟。", "Trên cây có một con chim."),
    ("鱼", "yú", "cá", "鱼缸里有很多鱼。", "Trong bể cá có nhiều cá."),
    ("兔子", "tùzi", "thỏ", "兔子耳朵很长。", "Thỏ có đôi tai rất dài."),
    ("牛", "niú", "bò", "农场里有很多牛。", "Trong nông trại có nhiều bò."),
    ("羊", "yáng", "cừu / dê", "羊毛很软。", "Lông cừu rất mềm."),
    ("马", "mǎ", "ngựa", "骑马很有趣。", "Cưỡi ngựa rất thú vị."),
    ("猪", "zhū", "lợn / heo", "猪在农场里。", "Lợn ở trong nông trại."),
    ("鸡", "jī", "gà", "鸡每天早上叫。", "Gà gáy mỗi sáng sớm."),
    ("熊猫", "xióngmāo", "gấu trúc", "熊猫是中国的国宝。", "Gấu trúc là quốc bảo của Trung Quốc."),
    ("老虎", "lǎohǔ", "hổ", "老虎很危险。", "Hổ rất nguy hiểm."),
    ("狮子", "shīzi", "sư tử", "狮子是丛林之王。", "Sư tử là vua của rừng xanh."),
    ("大象", "dàxiàng", "voi", "大象的鼻子很长。", "Vòi của voi rất dài."),

    # ─── MÀU SẮC & HÌNH DẠNG ─────────────────────────────────
    ("红色", "hóngsè", "màu đỏ", "红色象征幸运。", "Màu đỏ tượng trưng cho may mắn."),
    ("蓝色", "lánsè", "màu xanh dương", "我喜欢蓝色的天空。", "Tôi thích bầu trời màu xanh."),
    ("绿色", "lǜsè", "màu xanh lá", "绿色代表自然。", "Màu xanh đại diện cho thiên nhiên."),
    ("黄色", "huángsè", "màu vàng", "向日葵是黄色的。", "Hoa hướng dương có màu vàng."),
    ("白色", "báisè", "màu trắng", "雪是白色的。", "Tuyết có màu trắng."),
    ("黑色", "hēisè", "màu đen", "他穿了一件黑色衣服。", "Anh ấy mặc một chiếc áo màu đen."),
    ("粉色", "fěnsè", "màu hồng", "她喜欢粉色。", "Cô ấy thích màu hồng."),
    ("紫色", "zǐsè", "màu tím", "紫色的花很美。", "Hoa tím rất đẹp."),
    ("橙色", "chéngsè", "màu cam", "橙子是橙色的。", "Quả cam có màu cam."),
    ("大", "dà", "to / lớn", "这个房子很大。", "Ngôi nhà này rất to."),
    ("小", "xiǎo", "nhỏ / bé", "这只猫很小。", "Con mèo này rất nhỏ."),
    ("长", "cháng", "dài", "她的头发很长。", "Tóc cô ấy rất dài."),
    ("短", "duǎn", "ngắn", "他的头发很短。", "Tóc anh ấy rất ngắn."),
    ("高", "gāo", "cao", "他个子很高。", "Anh ấy rất cao."),
    ("矮", "ǎi", "thấp / lùn", "这棵树很矮。", "Cây này rất thấp."),
    ("圆", "yuán", "tròn", "月亮是圆的。", "Mặt trăng hình tròn."),
    ("方", "fāng", "vuông", "桌子是方形的。", "Bàn có hình vuông."),

    # ─── SỐ ĐẾM & THỜI GIAN ──────────────────────────────────
    ("今天", "jīntiān", "hôm nay", "今天天气很好。", "Hôm nay thời tiết rất tốt."),
    ("明天", "míngtiān", "ngày mai", "明天我要早起。", "Ngày mai tôi phải dậy sớm."),
    ("昨天", "zuótiān", "hôm qua", "昨天我去了超市。", "Hôm qua tôi đi siêu thị."),
    ("早上", "zǎoshang", "buổi sáng", "早上好！", "Chào buổi sáng!"),
    ("中午", "zhōngwǔ", "buổi trưa", "中午我们一起吃饭吧。", "Buổi trưa chúng ta ăn cùng nhé."),
    ("下午", "xiàwǔ", "buổi chiều", "下午我有课。", "Buổi chiều tôi có lớp học."),
    ("晚上", "wǎnshàng", "buổi tối", "晚上好！", "Chào buổi tối!"),
    ("星期一", "xīngqīyī", "thứ Hai", "星期一我很忙。", "Thứ Hai tôi rất bận."),
    ("星期五", "xīngqīwǔ", "thứ Sáu", "星期五是最开心的。", "Thứ Sáu là vui nhất."),
    ("周末", "zhōumò", "cuối tuần", "周末我喜欢休息。", "Cuối tuần tôi thích nghỉ ngơi."),
    ("月", "yuè", "tháng / mặt trăng", "这个月很快就过了。", "Tháng này trôi qua rất nhanh."),
    ("年", "nián", "năm", "新年快乐！", "Chúc mừng năm mới!"),
    ("小时", "xiǎoshí", "giờ (đơn vị)", "我睡了八个小时。", "Tôi ngủ tám tiếng."),
    ("分钟", "fēnzhōng", "phút", "再等十分钟。", "Đợi thêm mười phút."),
    ("春天", "chūntiān", "mùa xuân", "春天花都开了。", "Mùa xuân hoa đều nở."),
    ("夏天", "xiàtiān", "mùa hè", "夏天很热。", "Mùa hè rất nóng."),
    ("秋天", "qiūtiān", "mùa thu", "秋天树叶变黄了。", "Mùa thu lá cây chuyển vàng."),
    ("冬天", "dōngtiān", "mùa đông", "冬天很冷。", "Mùa đông rất lạnh."),
    ("过去", "guòqù", "quá khứ", "过去的事就让它过去吧。", "Chuyện quá khứ hãy để nó qua đi."),
    ("未来", "wèilái", "tương lai", "未来充满希望。", "Tương lai đầy hy vọng."),

    # ─── HOẠT ĐỘNG HẰNG NGÀY ─────────────────────────────────
    ("起床", "qǐchuáng", "thức dậy / ra khỏi giường", "我每天六点起床。", "Tôi dậy lúc 6 giờ mỗi ngày."),
    ("睡觉", "shuìjiào", "ngủ", "我晚上十一点睡觉。", "Tôi ngủ lúc 11 giờ tối."),
    ("刷牙", "shuāyá", "đánh răng", "早晚都要刷牙。", "Sáng tối đều phải đánh răng."),
    ("洗澡", "xǐzǎo", "tắm", "我每天晚上洗澡。", "Tôi tắm mỗi tối."),
    ("洗脸", "xǐliǎn", "rửa mặt", "早上起床先洗脸。", "Sáng dậy rửa mặt trước."),
    ("穿衣服", "chuān yīfú", "mặc quần áo", "快点穿衣服，要迟到了。", "Mặc quần áo nhanh lên, sắp trễ rồi."),
    ("做饭", "zuòfàn", "nấu cơm / nấu ăn", "妈妈在厨房做饭。", "Mẹ đang nấu ăn trong bếp."),
    ("工作", "gōngzuò", "làm việc / công việc", "我每天工作八小时。", "Tôi làm việc tám tiếng mỗi ngày."),
    ("学习", "xuéxí", "học tập / học", "我在努力学习汉语。", "Tôi đang cố gắng học tiếng Trung."),
    ("运动", "yùndòng", "vận động / tập thể dục", "每天运动对身体好。", "Vận động mỗi ngày tốt cho sức khỏe."),
    ("散步", "sànbù", "đi dạo", "晚饭后我去散步。", "Sau bữa tối tôi đi dạo."),
    ("跑步", "pǎobù", "chạy bộ", "我每天早上跑步。", "Tôi chạy bộ mỗi sáng."),
    ("骑车", "qí chē", "đạp xe / đi xe đạp", "我骑车去上班。", "Tôi đạp xe đi làm."),
    ("开车", "kāichē", "lái xe (ô tô)", "他不会开车。", "Anh ấy không biết lái xe."),
    ("购物", "gòuwù", "mua sắm", "周末我喜欢去购物。", "Cuối tuần tôi thích đi mua sắm."),
    ("打扫", "dǎsǎo", "dọn dẹp / quét dọn", "我今天打扫了房间。", "Hôm nay tôi dọn dẹp phòng."),
    ("洗衣服", "xǐ yīfú", "giặt quần áo", "星期天我洗衣服。", "Chủ nhật tôi giặt quần áo."),
    ("看书", "kàn shū", "đọc sách", "我每天晚上看书。", "Tôi đọc sách mỗi tối."),
    ("听音乐", "tīng yīnyuè", "nghe nhạc", "我喜欢听音乐放松。", "Tôi thích nghe nhạc để thư giãn."),
    ("看电视", "kàn diànshì", "xem tivi", "晚上我们看电视。", "Buổi tối chúng tôi xem tivi."),
    ("玩手机", "wán shǒujī", "chơi điện thoại", "少玩手机，多看书。", "Ít chơi điện thoại, đọc sách nhiều hơn."),
    ("聊天", "liáotiān", "trò chuyện / chat", "我们聊了很久的天。", "Chúng tôi trò chuyện rất lâu."),
    ("开会", "kāihuì", "họp / tổ chức cuộc họp", "下午三点开会。", "Chiều 3 giờ họp."),
    ("上班", "shàngbān", "đi làm / bắt đầu ca làm", "我八点上班。", "Tôi đi làm lúc 8 giờ."),
    ("下班", "xiàbān", "tan làm / kết thúc ca làm", "我五点下班。", "Tôi tan làm lúc 5 giờ."),
    ("休息", "xiūxi", "nghỉ ngơi", "好好休息一下。", "Nghỉ ngơi tốt một chút."),
    ("旅行", "lǚxíng", "du lịch", "我想去中国旅行。", "Tôi muốn đi du lịch Trung Quốc."),
    ("拍照", "pāizhào", "chụp ảnh", "我们一起拍照吧！", "Chúng ta chụp ảnh cùng nhau nhé!"),
    ("唱歌", "chànggē", "hát", "她唱歌很好听。", "Cô ấy hát rất hay."),
    ("跳舞", "tiàowǔ", "nhảy múa", "她非常会跳舞。", "Cô ấy nhảy múa rất giỏi."),

    # ─── NHÀ Ở & ĐỒ DÙNG ─────────────────────────────────────
    ("家", "jiā", "nhà / gia đình", "我回家了。", "Tôi về nhà rồi."),
    ("房间", "fángjiān", "phòng", "我的房间很整洁。", "Phòng tôi rất gọn gàng."),
    ("卧室", "wòshì", "phòng ngủ", "卧室里有一张大床。", "Trong phòng ngủ có một cái giường lớn."),
    ("客厅", "kètīng", "phòng khách", "客厅很宽敞。", "Phòng khách rất rộng rãi."),
    ("厨房", "chúfáng", "nhà bếp", "妈妈在厨房里做饭。", "Mẹ đang nấu ăn trong bếp."),
    ("卫生间", "wèishēngjiān", "nhà vệ sinh / phòng tắm", "卫生间在右边。", "Nhà vệ sinh ở bên phải."),
    ("门", "mén", "cửa", "请关门。", "Làm ơn đóng cửa."),
    ("窗户", "chuānghù", "cửa sổ", "打开窗户，通通风。", "Mở cửa sổ thông gió."),
    ("床", "chuáng", "giường", "我的床很舒服。", "Giường tôi rất thoải mái."),
    ("桌子", "zhuōzi", "bàn", "桌子上有很多书。", "Trên bàn có nhiều sách."),
    ("椅子", "yǐzi", "ghế", "请坐椅子。", "Mời ngồi ghế."),
    ("沙发", "shāfā", "ghế sofa", "我喜欢坐在沙发上看书。", "Tôi thích ngồi trên sofa đọc sách."),
    ("冰箱", "bīngxiāng", "tủ lạnh", "冰箱里有水果。", "Trong tủ lạnh có trái cây."),
    ("洗衣机", "xǐyījī", "máy giặt", "洗衣机坏了。", "Máy giặt bị hỏng rồi."),
    ("电视", "diànshì", "ti vi", "新电视很大。", "Ti vi mới rất to."),
    ("空调", "kōngtiáo", "máy điều hòa", "夏天开空调。", "Mùa hè bật điều hòa."),
    ("灯", "dēng", "đèn", "请开灯。", "Làm ơn bật đèn."),
    ("电话", "diànhuà", "điện thoại", "他打来了一个电话。", "Anh ấy gọi điện đến."),
    ("钥匙", "yàoshi", "chìa khóa", "我找不到钥匙。", "Tôi không tìm thấy chìa khóa."),
    ("垃圾", "lājī", "rác", "请把垃圾扔掉。", "Làm ơn vứt rác đi."),

    # ─── QUẦN ÁO & THỜI TRANG ────────────────────────────────
    ("衣服", "yīfú", "quần áo", "她的衣服很漂亮。", "Quần áo cô ấy rất đẹp."),
    ("上衣", "shàngyī", "áo (phần trên)", "这件上衣多少钱？", "Chiếc áo này bao nhiêu tiền?"),
    ("裤子", "kùzi", "quần", "这条裤子太紧了。", "Cái quần này quá chật."),
    ("裙子", "qúnzi", "váy", "她穿了一条漂亮的裙子。", "Cô ấy mặc một chiếc váy đẹp."),
    ("T恤", "T xù", "áo phông", "我喜欢穿T恤。", "Tôi thích mặc áo phông."),
    ("外套", "wàitào", "áo khoác ngoài", "天冷要穿外套。", "Trời lạnh phải mặc áo khoác."),
    ("鞋子", "xiézi", "giày dép", "这双鞋子很舒服。", "Đôi giày này rất thoải mái."),
    ("袜子", "wàzi", "tất / vớ", "我的袜子丢了一只。", "Tôi mất một chiếc tất rồi."),
    ("帽子", "màozi", "mũ / nón", "戴帽子防晒。", "Đội mũ chống nắng."),
    ("围巾", "wéijīn", "khăn quàng cổ", "冬天我会戴围巾。", "Mùa đông tôi sẽ đeo khăn."),
    ("眼镜", "yǎnjìng", "kính mắt", "他戴眼镜。", "Anh ấy đeo kính."),
    ("包", "bāo", "túi xách", "她的包很贵。", "Túi xách của cô ấy rất đắt."),
    ("手表", "shǒubiǎo", "đồng hồ đeo tay", "他戴着一块手表。", "Anh ấy đeo một chiếc đồng hồ."),

    # ─── PHƯƠNG TIỆN ĐI LẠI ──────────────────────────────────
    ("车", "chē", "xe", "这辆车很贵。", "Chiếc xe này rất đắt."),
    ("公交车", "gōngjiāochē", "xe buýt", "我坐公交车上班。", "Tôi đi xe buýt đi làm."),
    ("地铁", "dìtiě", "tàu điện ngầm / metro", "地铁比公交快。", "Tàu điện ngầm nhanh hơn xe buýt."),
    ("出租车", "chūzūchē", "taxi", "我叫了一辆出租车。", "Tôi gọi một chiếc taxi."),
    ("飞机", "fēijī", "máy bay", "我坐飞机去中国。", "Tôi đi máy bay đến Trung Quốc."),
    ("火车", "huǒchē", "tàu hỏa", "火车票买好了。", "Vé tàu hỏa đã mua xong rồi."),
    ("船", "chuán", "thuyền / tàu thủy", "我们坐船旅行。", "Chúng tôi đi thuyền du lịch."),
    ("摩托车", "mótuōchē", "xe máy", "越南人常骑摩托车。", "Người Việt Nam thường đi xe máy."),
    ("自行车", "zìxíngchē", "xe đạp", "骑自行车很健康。", "Đi xe đạp rất tốt cho sức khỏe."),
    ("路", "lù", "đường / con đường", "这条路很堵。", "Con đường này rất tắc."),
    ("车站", "chēzhàn", "bến xe / trạm xe", "车站在哪里？", "Bến xe ở đâu?"),
    ("机场", "jīchǎng", "sân bay", "机场离市区很远。", "Sân bay cách trung tâm thành phố xa."),
    ("地图", "dìtú", "bản đồ", "我用手机看地图。", "Tôi dùng điện thoại xem bản đồ."),

    # ─── THIÊN NHIÊN & THỜI TIẾT ─────────────────────────────
    ("天气", "tiānqì", "thời tiết", "今天天气怎么样？", "Thời tiết hôm nay như thế nào?"),
    ("晴天", "qíngtiān", "trời nắng đẹp", "今天是晴天。", "Hôm nay trời nắng đẹp."),
    ("下雨", "xià yǔ", "trời mưa", "今天下雨了。", "Hôm nay trời mưa."),
    ("下雪", "xià xuě", "tuyết rơi", "北方冬天下雪。", "Miền bắc mùa đông tuyết rơi."),
    ("刮风", "guā fēng", "trời nổi gió", "今天刮大风。", "Hôm nay gió to."),
    ("热", "rè", "nóng", "今天很热，三十八度。", "Hôm nay rất nóng, 38 độ."),
    ("冷", "lěng", "lạnh", "冬天很冷。", "Mùa đông rất lạnh."),
    ("温暖", "wēnnuǎn", "ấm áp", "春天很温暖。", "Mùa xuân rất ấm áp."),
    ("凉快", "liángkuài", "mát mẻ", "秋天的风很凉快。", "Gió mùa thu rất mát mẻ."),
    ("太阳", "tàiyáng", "mặt trời", "太阳出来了！", "Mặt trời mọc rồi!"),
    ("月亮", "yuèliang", "mặt trăng", "今晚月亮很圆。", "Đêm nay trăng tròn."),
    ("星星", "xīngxīng", "ngôi sao", "夜晚星星很多。", "Đêm nhiều ngôi sao."),
    ("云", "yún", "mây", "天上的云很漂亮。", "Những đám mây trên bầu trời rất đẹp."),
    ("风", "fēng", "gió", "今天风很大。", "Hôm nay gió rất lớn."),
    ("雨", "yǔ", "mưa", "雨停了。", "Mưa đã tạnh rồi."),
    ("雪", "xuě", "tuyết", "第一次看到雪很兴奋。", "Lần đầu thấy tuyết rất hứng khởi."),
    ("山", "shān", "núi", "那座山很高。", "Ngọn núi kia rất cao."),
    ("河", "hé", "sông", "我家旁边有一条河。", "Cạnh nhà tôi có một con sông."),
    ("海", "hǎi", "biển", "我喜欢去海边玩。", "Tôi thích đi chơi bờ biển."),
    ("花", "huā", "hoa", "她喜欢种花。", "Cô ấy thích trồng hoa."),
    ("树", "shù", "cây", "公园里有很多树。", "Trong công viên có nhiều cây."),
    ("草", "cǎo", "cỏ", "草地上有露水。", "Trên thảm cỏ có sương."),
    ("空气", "kōngqì", "không khí", "这里空气很清新。", "Không khí ở đây rất trong lành."),

    # ─── CÔNG VIỆC & HỌC TẬP ─────────────────────────────────
    ("老师", "lǎoshī", "thầy giáo / cô giáo", "老师讲得很清楚。", "Thầy giảng rất rõ ràng."),
    ("学生", "xuéshēng", "học sinh / sinh viên", "我是大学生。", "Tôi là sinh viên đại học."),
    ("学校", "xuéxiào", "trường học", "我的学校很大。", "Trường của tôi rất to."),
    ("大学", "dàxué", "đại học", "她在读大学。", "Cô ấy đang học đại học."),
    ("教室", "jiàoshì", "phòng học / lớp học", "教室里有三十个学生。", "Lớp học có ba mươi học sinh."),
    ("课本", "kèběn", "sách giáo khoa", "课本放在书包里。", "Sách giáo khoa để trong cặp."),
    ("作业", "zuòyè", "bài tập về nhà", "今天作业很多。", "Hôm nay bài tập rất nhiều."),
    ("考试", "kǎoshì", "thi / kỳ thi", "下周有考试。", "Tuần sau có kỳ thi."),
    ("成绩", "chéngjì", "điểm số / thành tích", "这次考试成绩很好。", "Điểm thi lần này rất tốt."),
    ("医生", "yīshēng", "bác sĩ", "他是一位好医生。", "Anh ấy là một bác sĩ giỏi."),
    ("护士", "hùshi", "y tá", "护士对病人很耐心。", "Y tá rất kiên nhẫn với bệnh nhân."),
    ("工程师", "gōngchéngshī", "kỹ sư", "他是一名工程师。", "Anh ấy là một kỹ sư."),
    ("厨师", "chúshī", "đầu bếp", "这家餐厅的厨师很厉害。", "Đầu bếp của nhà hàng này rất giỏi."),
    ("司机", "sījī", "tài xế", "公交车司机很友好。", "Tài xế xe buýt rất thân thiện."),
    ("公司", "gōngsī", "công ty", "我在一家大公司工作。", "Tôi làm việc ở một công ty lớn."),
    ("办公室", "bàngōngshì", "văn phòng", "办公室在二楼。", "Văn phòng ở tầng hai."),
    ("工资", "gōngzī", "lương", "这个月工资发了。", "Tháng này lương đã được phát."),
    ("简历", "jiǎnlì", "hồ sơ / CV", "我写了一份简历。", "Tôi đã viết một bản CV."),
    ("面试", "miànshì", "phỏng vấn", "明天我有面试。", "Ngày mai tôi có buổi phỏng vấn."),
    ("同事", "tóngshì", "đồng nghiệp", "同事们都很好。", "Các đồng nghiệp đều rất tốt."),

    # ─── SỨC KHỎE & Y TẾ ────────────────────────────────────
    ("健康", "jiànkāng", "khỏe mạnh / sức khỏe", "健康比什么都重要。", "Sức khỏe quan trọng hơn tất cả."),
    ("生病", "shēngbìng", "bị bệnh / ốm", "我今天生病了。", "Hôm nay tôi bị bệnh."),
    ("发烧", "fāshāo", "sốt", "孩子发烧了。", "Đứa trẻ bị sốt rồi."),
    ("咳嗽", "késòu", "ho", "我一直在咳嗽。", "Tôi cứ ho mãi."),
    ("头疼", "tóuténg", "đau đầu", "我头疼，不舒服。", "Tôi đau đầu, không thoải mái."),
    ("肚子疼", "dùzi téng", "đau bụng", "我肚子疼，吃坏了。", "Tôi đau bụng, ăn phải thứ không tốt."),
    ("医院", "yīyuàn", "bệnh viện", "他去医院检查了。", "Anh ấy đến bệnh viện kiểm tra."),
    ("药", "yào", "thuốc", "医生给我开了药。", "Bác sĩ kê thuốc cho tôi."),
    ("打针", "dǎ zhēn", "tiêm thuốc", "我害怕打针。", "Tôi sợ tiêm thuốc."),
    ("手术", "shǒushù", "phẫu thuật / mổ", "他做了一个小手术。", "Anh ấy đã phẫu thuật nhỏ."),
    ("过敏", "guòmǐn", "dị ứng", "我对花粉过敏。", "Tôi bị dị ứng với phấn hoa."),
    ("血压", "xuèyā", "huyết áp", "要注意控制血压。", "Cần chú ý kiểm soát huyết áp."),
    ("口罩", "kǒuzhào", "khẩu trang", "出门要戴口罩。", "Ra ngoài phải đeo khẩu trang."),

    # ─── MUA SẮM & TIỀN BẠC ──────────────────────────────────
    ("钱", "qián", "tiền", "我没有钱。", "Tôi không có tiền."),
    ("贵", "guì", "đắt", "这个太贵了！", "Cái này quá đắt!"),
    ("便宜", "piányí", "rẻ / giảm giá", "这件衣服很便宜。", "Chiếc áo này rất rẻ."),
    ("打折", "dǎzhé", "giảm giá / sale", "这家店打八折。", "Cửa hàng này giảm 20%."),
    ("超市", "chāoshì", "siêu thị", "我去超市买东西。", "Tôi đến siêu thị mua đồ."),
    ("商店", "shāngdiàn", "cửa hàng / tiệm", "街上有很多商店。", "Trên phố có nhiều cửa hàng."),
    ("银行", "yínháng", "ngân hàng", "我去银行取钱。", "Tôi đến ngân hàng rút tiền."),
    ("收据", "shōujù", "hóa đơn / biên lai", "请给我收据。", "Làm ơn cho tôi hóa đơn."),
    ("信用卡", "xìnyòngkǎ", "thẻ tín dụng", "可以用信用卡吗？", "Có thể dùng thẻ tín dụng không?"),
    ("支付宝", "zhīfùbǎo", "Alipay (ứng dụng thanh toán)", "用支付宝付款。", "Thanh toán bằng Alipay."),

    # ─── CẢM XÚC & TÍNH CÁCH ─────────────────────────────────
    ("高兴", "gāoxìng", "vui mừng / vui sướng", "见到你我很高兴。", "Tôi rất vui khi gặp bạn."),
    ("开心", "kāixīn", "vui vẻ / hạnh phúc", "今天很开心。", "Hôm nay rất vui."),
    ("难过", "nánguò", "buồn / đau lòng", "她听到消息很难过。", "Cô ấy nghe tin rất buồn."),
    ("生气", "shēngqì", "tức giận", "他说了什么让你生气？", "Anh ấy nói gì khiến bạn tức giận?"),
    ("担心", "dānxīn", "lo lắng", "妈妈很担心我。", "Mẹ rất lo lắng cho tôi."),
    ("紧张", "jǐnzhāng", "căng thẳng / hồi hộp", "考试前很紧张。", "Trước khi thi rất hồi hộp."),
    ("放松", "fàngsōng", "thư giãn", "周末要好好放松。", "Cuối tuần cần thư giãn thật tốt."),
    ("累", "lèi", "mệt", "今天工作太累了。", "Hôm nay làm việc mệt quá."),
    ("害怕", "hàipà", "sợ hãi", "他害怕蜘蛛。", "Anh ấy sợ nhện."),
    ("惊讶", "jīngyà", "ngạc nhiên / bất ngờ", "她听到消息很惊讶。", "Cô ấy rất ngạc nhiên khi nghe tin."),
    ("骄傲", "jiāo'ào", "tự hào / kiêu ngạo", "妈妈为我感到骄傲。", "Mẹ tự hào về tôi."),
    ("聪明", "cōngmíng", "thông minh", "她是个聪明的孩子。", "Cô bé là một đứa trẻ thông minh."),
    ("努力", "nǔlì", "nỗ lực / chăm chỉ", "要努力才能成功。", "Phải nỗ lực mới có thể thành công."),
    ("懒", "lǎn", "lười biếng", "今天有点懒，不想动。", "Hôm nay hơi lười, không muốn vận động."),
    ("善良", "shànliáng", "tốt bụng / hiền lành", "她是一个善良的人。", "Cô ấy là một người tốt bụng."),
    ("有趣", "yǒuqù", "thú vị", "这本书很有趣。", "Quyển sách này rất thú vị."),

    # ─── SỞ THÍCH & GIẢI TRÍ ─────────────────────────────────
    ("爱好", "àihào", "sở thích", "你的爱好是什么？", "Sở thích của bạn là gì?"),
    ("音乐", "yīnyuè", "âm nhạc", "我喜欢听音乐。", "Tôi thích nghe âm nhạc."),
    ("电影", "diànyǐng", "phim điện ảnh", "今晚去看电影吗？", "Tối nay đi xem phim không?"),
    ("游戏", "yóuxì", "trò chơi", "他喜欢玩游戏。", "Anh ấy thích chơi game."),
    ("书", "shū", "sách", "我每天都看书。", "Tôi đọc sách mỗi ngày."),
    ("画画", "huàhuà", "vẽ tranh", "她从小喜欢画画。", "Cô ấy thích vẽ từ nhỏ."),
    ("摄影", "shèyǐng", "nhiếp ảnh / chụp ảnh", "他的摄影技术很好。", "Kỹ thuật chụp ảnh của anh ấy rất tốt."),
    ("足球", "zúqiú", "bóng đá", "他很喜欢踢足球。", "Anh ấy rất thích chơi bóng đá."),
    ("篮球", "lánqiú", "bóng rổ", "他每周打篮球。", "Anh ấy chơi bóng rổ mỗi tuần."),
    ("游泳", "yóuyǒng", "bơi lội", "夏天去游泳很好。", "Mùa hè đi bơi rất tốt."),
    ("瑜伽", "yújiā", "yoga", "她每天早上练瑜伽。", "Mỗi sáng cô ấy tập yoga."),
    ("钓鱼", "diàoyú", "câu cá", "爸爸喜欢周末钓鱼。", "Bố thích câu cá vào cuối tuần."),
    ("种花", "zhòng huā", "trồng hoa", "她喜欢在阳台种花。", "Cô ấy thích trồng hoa trên ban công."),
    ("旅游", "lǚyóu", "du lịch / tham quan", "我的爱好是旅游。", "Sở thích của tôi là du lịch."),
    ("烹饪", "pēngrèn", "nấu nướng", "她的烹饪技术很好。", "Kỹ thuật nấu ăn của cô ấy rất tốt."),

    # ─── ĐỊA ĐIỂM & PHƯƠNG HƯỚNG ─────────────────────────────
    ("左", "zuǒ", "trái", "向左转。", "Rẽ trái."),
    ("右", "yòu", "phải", "向右转。", "Rẽ phải."),
    ("上", "shàng", "trên / lên", "书在桌子上。", "Sách ở trên bàn."),
    ("下", "xià", "dưới / xuống", "猫在桌子下。", "Mèo ở dưới bàn."),
    ("前", "qián", "trước", "前面是学校。", "Phía trước là trường học."),
    ("后", "hòu", "sau", "后面是停车场。", "Phía sau là bãi đỗ xe."),
    ("附近", "fùjìn", "gần đây / lân cận", "附近有超市吗？", "Gần đây có siêu thị không?"),
    ("公园", "gōngyuán", "công viên", "我喜欢在公园散步。", "Tôi thích đi dạo trong công viên."),
    ("图书馆", "túshūguǎn", "thư viện", "我在图书馆学习。", "Tôi học ở thư viện."),
    ("邮局", "yóujú", "bưu điện", "我去邮局寄信。", "Tôi đến bưu điện gửi thư."),
    ("药店", "yàodiàn", "hiệu thuốc", "附近有药店吗？", "Gần đây có hiệu thuốc không?"),
    ("餐厅", "cāntīng", "nhà hàng / quán ăn", "这家餐厅很有名。", "Nhà hàng này rất nổi tiếng."),
    ("咖啡店", "kāfēidiàn", "quán cà phê", "我们去咖啡店坐坐。", "Chúng ta đến quán cà phê ngồi nhé."),
    ("酒店", "jiǔdiàn", "khách sạn", "我预订了一个酒店。", "Tôi đã đặt một khách sạn."),
    ("车站", "chēzhàn", "ga xe / bến xe", "火车站在哪里？", "Ga xe lửa ở đâu?"),
    ("城市", "chéngshì", "thành phố", "上海是一个大城市。", "Thượng Hải là một thành phố lớn."),
    ("农村", "nóngcūn", "nông thôn / vùng quê", "他来自农村。", "Anh ấy đến từ nông thôn."),
    ("北京", "Běijīng", "Bắc Kinh", "北京是中国的首都。", "Bắc Kinh là thủ đô của Trung Quốc."),
    ("上海", "Shànghǎi", "Thượng Hải", "上海是个繁华的城市。", "Thượng Hải là một thành phố sầm uất."),
    ("中国", "Zhōngguó", "Trung Quốc", "中国有很多好吃的食物。", "Trung Quốc có rất nhiều món ăn ngon."),

    # ─── CÔNG NGHỆ & ĐỜI SỐNG HIỆN ĐẠI ─────────────────────
    ("手机", "shǒujī", "điện thoại di động", "我的手机没电了。", "Điện thoại tôi hết pin rồi."),
    ("电脑", "diànnǎo", "máy tính", "我用电脑工作。", "Tôi dùng máy tính để làm việc."),
    ("网络", "wǎngluò", "mạng internet / mạng lưới", "这里网络很慢。", "Mạng ở đây rất chậm."),
    ("WiFi", "WiFi", "wifi", "有WiFi密码吗？", "Có mật khẩu wifi không?"),
    ("软件", "ruǎnjiàn", "phần mềm", "我下载了一个软件。", "Tôi đã tải một phần mềm."),
    ("应用", "yìngyòng", "ứng dụng (app)", "这个应用很好用。", "Ứng dụng này rất tiện dụng."),
    ("密码", "mìmǎ", "mật khẩu", "忘记密码了。", "Quên mật khẩu rồi."),
    ("发短信", "fā duǎnxìn", "nhắn tin", "给我发短信吧。", "Nhắn tin cho tôi nhé."),
    ("视频通话", "shìpín tōnghuà", "gọi video / video call", "我们视频通话吧。", "Chúng ta gọi video nhé."),
    ("充电", "chōngdiàn", "sạc pin", "手机需要充电了。", "Điện thoại cần sạc rồi."),

    # ─── TỪ VỰNG QUAN TRỌNG KHÁC ─────────────────────────────
    ("帮助", "bāngzhù", "giúp đỡ", "谢谢你的帮助！", "Cảm ơn sự giúp đỡ của bạn!"),
    ("问题", "wèntí", "câu hỏi / vấn đề", "你有什么问题吗？", "Bạn có câu hỏi gì không?"),
    ("回答", "huídá", "trả lời", "请回答我的问题。", "Làm ơn trả lời câu hỏi của tôi."),
    ("说", "shuō", "nói", "你说什么？", "Bạn nói gì vậy?"),
    ("听", "tīng", "nghe", "认真听老师讲课。", "Chăm chú nghe thầy giảng bài."),
    ("看", "kàn", "nhìn / xem", "看黑板。", "Nhìn lên bảng."),
    ("写", "xiě", "viết", "请把名字写在这里。", "Làm ơn viết tên vào đây."),
    ("读", "dú", "đọc", "大声读课文。", "Đọc to bài học."),
    ("想", "xiǎng", "muốn / nghĩ", "我想学习汉语。", "Tôi muốn học tiếng Trung."),
    ("喜欢", "xǐhuān", "thích / yêu thích", "我喜欢吃越南食物。", "Tôi thích ăn đồ ăn Việt Nam."),
    ("爱", "ài", "yêu", "我爱我的家人。", "Tôi yêu gia đình mình."),
    ("需要", "xūyào", "cần / cần thiết", "我需要你的帮助。", "Tôi cần sự giúp đỡ của bạn."),
    ("有", "yǒu", "có", "我有一个梦想。", "Tôi có một giấc mơ."),
    ("没有", "méiyǒu", "không có", "我没有时间。", "Tôi không có thời gian."),
    ("很", "hěn", "rất", "今天很冷。", "Hôm nay rất lạnh."),
    ("非常", "fēicháng", "rất / vô cùng", "这里的风景非常美。", "Phong cảnh ở đây rất đẹp."),
    ("一点", "yīdiǎn", "một chút / một ít", "我会说一点汉语。", "Tôi biết nói một chút tiếng Trung."),
    ("一下", "yīxià", "một lúc / thử", "等一下！", "Đợi một chút!"),
    ("已经", "yǐjīng", "đã / rồi", "我已经吃了。", "Tôi đã ăn rồi."),
    ("还没", "hái méi", "chưa", "我还没准备好。", "Tôi chưa chuẩn bị xong."),
    ("马上", "mǎshàng", "ngay bây giờ / sắp", "我马上来。", "Tôi đến ngay."),
    ("慢慢", "mànmàn", "từ từ / chậm chậm", "慢慢说，我听不懂。", "Nói chậm thôi, tôi không hiểu."),
    ("一起", "yīqǐ", "cùng nhau", "我们一起加油！", "Chúng ta cùng nhau cố lên!"),
    ("真的", "zhēnde", "thật sự / thực sự", "真的吗？太好了！", "Thật sao? Tốt quá!"),
    ("当然", "dāngrán", "tất nhiên / dĩ nhiên", "当然可以！", "Tất nhiên được!"),

    # ─── TRƯỜNG HỌC & VĂN PHÒNG PHẨM ───────────────────────
    ("笔", "bǐ", "bút", "借我一支笔。", "Cho tôi mượn một cây bút."),
    ("铅笔", "qiānbǐ", "bút chì", "用铅笔写可以擦掉。", "Viết bằng bút chì có thể tẩy được."),
    ("本子", "běnzi", "vở / quyển sổ", "我买了一个新本子。", "Tôi mua một quyển vở mới."),
    ("橡皮", "xiàngpí", "tẩy (gôm)", "把错误擦掉。", "Tẩy lỗi sai đi."),
    ("尺子", "chǐzi", "thước kẻ", "量一下这张纸的长度。", "Đo chiều dài tờ giấy này."),
    ("书包", "shūbāo", "cặp sách / ba lô học sinh", "书包很重。", "Cặp sách rất nặng."),
    ("黑板", "hēibǎn", "bảng (đen)", "老师在黑板上写字。", "Thầy viết chữ trên bảng."),
    ("粉笔", "fěnbǐ", "phấn viết bảng", "白色粉笔写得很清楚。", "Phấn trắng viết rất rõ."),
    ("字典", "zìdiǎn", "từ điển", "查一下字典。", "Tra từ điển xem."),
    ("毕业", "bìyè", "tốt nghiệp", "她明年毕业。", "Năm sau cô ấy tốt nghiệp."),

    # ─── BƯU ĐIỆN & LIÊN LẠC ─────────────────────────────────
    ("信", "xìn", "thư", "我收到了一封信。", "Tôi nhận được một lá thư."),
    ("信封", "xìnfēng", "phong bì", "把信放进信封里。", "Cho thư vào phong bì."),
    ("邮票", "yóupiào", "tem thư", "这张邮票很漂亮。", "Con tem này rất đẹp."),
    ("电子邮件", "diànzǐ yóujiàn", "thư điện tử / email", "给我发电子邮件。", "Gửi email cho tôi."),
    ("地址", "dìzhǐ", "địa chỉ", "请写下你的地址。", "Hãy viết địa chỉ của bạn."),

    # ─── NGÂN HÀNG & TÀI CHÍNH ───────────────────────────────
    ("存钱", "cún qián", "gửi tiền / để dành", "每个月存一点钱。", "Mỗi tháng tiết kiệm một ít tiền."),
    ("取钱", "qǔ qián", "rút tiền", "我去ATM取钱。", "Tôi đến ATM rút tiền."),
    ("转账", "zhuǎnzhàng", "chuyển khoản", "可以转账给我吗？", "Bạn có thể chuyển khoản cho tôi không?"),
    ("账单", "zhàngdān", "hóa đơn / bill", "电费账单来了。", "Hóa đơn điện đã đến."),
    ("预算", "yùsuàn", "ngân sách / dự toán", "这个月预算不够了。", "Tháng này ngân sách không đủ rồi."),

    # ─── GIA ĐÌNH & CÁC MỐI QUAN HỆ ─────────────────────────
    ("结婚", "jiéhūn", "kết hôn", "他们去年结婚了。", "Họ kết hôn năm ngoái."),
    ("离婚", "líhūn", "ly hôn", "", ""),
    ("恋爱", "liàn'ài", "yêu đương", "他们在恋爱。", "Họ đang yêu nhau."),
    ("男朋友", "nán péngyǒu", "bạn trai", "她有男朋友了。", "Cô ấy có bạn trai rồi."),
    ("女朋友", "nǚ péngyǒu", "bạn gái", "他的女朋友很漂亮。", "Bạn gái anh ấy rất đẹp."),
    ("婚礼", "hūnlǐ", "đám cưới", "我参加了朋友的婚礼。", "Tôi tham dự đám cưới của bạn."),
    ("生日", "shēngrì", "sinh nhật", "生日快乐！", "Chúc mừng sinh nhật!"),
    ("礼物", "lǐwù", "quà tặng", "我给她买了礼物。", "Tôi mua quà cho cô ấy."),
    ("节日", "jiérì", "ngày lễ / lễ tết", "春节是中国最重要的节日。", "Tết Nguyên Đán là lễ quan trọng nhất của Trung Quốc."),
    ("春节", "Chūnjié", "Tết Nguyên Đán", "春节要回家团圆。", "Tết Nguyên Đán phải về nhà sum họp."),

    # ─── ĐỒ VẬT HẰNG NGÀY ────────────────────────────────────
    ("镜子", "jìngzi", "gương", "照镜子整理仪容。", "Nhìn gương chỉnh sửa diện mạo."),
    ("毛巾", "máojīn", "khăn tắm", "洗完澡用毛巾擦干。", "Tắm xong dùng khăn lau khô."),
    ("牙刷", "yáshuā", "bàn chải đánh răng", "每天换新牙刷。", "Thay bàn chải đánh răng mới mỗi ngày."),
    ("牙膏", "yágāo", "kem đánh răng", "牙膏用完了。", "Kem đánh răng hết rồi."),
    ("香皂", "xiāngsào", "xà phòng", "用香皂洗手。", "Dùng xà phòng rửa tay."),
    ("洗发水", "xǐfàshuǐ", "dầu gội đầu", "我喜欢用这款洗发水。", "Tôi thích dùng loại dầu gội này."),
    ("护肤品", "hùfūpǐn", "sản phẩm chăm sóc da", "她每天用护肤品。", "Cô ấy dùng sản phẩm dưỡng da mỗi ngày."),
    ("纸巾", "zhǐjīn", "khăn giấy", "递给我一张纸巾。", "Đưa cho tôi một tờ khăn giấy."),
    ("雨伞", "yǔsǎn", "ô / dù (che mưa)", "出门记得带雨伞。", "Ra ngoài nhớ mang ô."),
    ("手提包", "shǒutíbāo", "túi xách tay", "她的手提包很贵。", "Túi xách của cô ấy rất đắt."),

    # ─── CÁC ĐỘNG TỪ THÔNG DỤNG ──────────────────────────────
    ("去", "qù", "đi / đến", "我去学校。", "Tôi đến trường."),
    ("来", "lái", "đến / lại", "请进来。", "Mời vào."),
    ("回", "huí", "về / trở lại", "我回家了。", "Tôi về nhà rồi."),
    ("走", "zǒu", "đi bộ / rời đi", "我们走吧。", "Chúng ta đi thôi."),
    ("跑", "pǎo", "chạy", "快跑！", "Chạy nhanh!"),
    ("坐", "zuò", "ngồi", "请坐。", "Mời ngồi."),
    ("站", "zhàn", "đứng", "请站起来。", "Làm ơn đứng dậy."),
    ("拿", "ná", "cầm / lấy", "帮我拿一下这个。", "Giúp tôi cầm cái này."),
    ("放", "fàng", "đặt / để", "把书放在桌上。", "Đặt sách lên bàn."),
    ("开", "kāi", "mở / bật / lái", "请开门。", "Làm ơn mở cửa."),
    ("关", "guān", "đóng / tắt", "请关灯。", "Làm ơn tắt đèn."),
    ("买", "mǎi", "mua", "我去买菜。", "Tôi đi mua rau."),
    ("卖", "mài", "bán", "这里卖水果。", "Ở đây bán trái cây."),
    ("找", "zhǎo", "tìm kiếm", "我在找我的钥匙。", "Tôi đang tìm chìa khóa."),
    ("用", "yòng", "dùng / sử dụng", "你用筷子吗？", "Bạn dùng đũa không?"),
    ("给", "gěi", "cho / đưa", "给我一杯水。", "Cho tôi một ly nước."),
    ("叫", "jiào", "gọi / tên là", "他叫什么名字？", "Anh ấy tên là gì?"),
    ("等", "děng", "đợi / chờ", "等我一下。", "Đợi tôi một chút."),
    ("送", "sòng", "tặng / tiễn đưa", "我送你回家。", "Tôi tiễn bạn về nhà."),
    ("接", "jiē", "đón / nhận / nghe (điện thoại)", "我去机场接你。", "Tôi đến sân bay đón bạn."),

    # ─── MÔ TẢ & TRẠNG THÁI ──────────────────────────────────
    ("漂亮", "piàoliang", "đẹp / xinh", "她很漂亮。", "Cô ấy rất đẹp."),
    ("帅", "shuài", "đẹp trai / phong độ", "他很帅。", "Anh ấy rất đẹp trai."),
    ("干净", "gānjìng", "sạch sẽ", "房间很干净。", "Phòng rất sạch sẽ."),
    ("脏", "zāng", "bẩn", "手很脏，快去洗。", "Tay rất bẩn, đi rửa đi."),
    ("新", "xīn", "mới", "这是新买的。", "Đây là mới mua."),
    ("旧", "jiù", "cũ", "这件衣服太旧了。", "Chiếc áo này quá cũ rồi."),
    ("快", "kuài", "nhanh", "快点，要迟到了！", "Nhanh lên, sắp muộn rồi!"),
    ("慢", "màn", "chậm", "请说慢一点。", "Xin nói chậm hơn một chút."),
    ("多", "duō", "nhiều", "人太多了。", "Người quá nhiều."),
    ("少", "shǎo", "ít", "时间太少了。", "Thời gian quá ít."),
    ("重要", "zhòngyào", "quan trọng", "健康是最重要的。", "Sức khỏe là quan trọng nhất."),
    ("简单", "jiǎndān", "đơn giản / dễ dàng", "这道题很简单。", "Bài toán này rất đơn giản."),
    ("难", "nán", "khó", "这道题很难。", "Bài toán này rất khó."),
    ("容易", "róngyì", "dễ dàng", "这个很容易做到。", "Cái này rất dễ làm được."),
    ("正确", "zhèngquè", "đúng / chính xác", "你的答案是正确的。", "Câu trả lời của bạn là đúng."),
    ("错误", "cuòwù", "sai / lỗi", "这里有一个错误。", "Ở đây có một lỗi sai."),

    # ─── BỔ SUNG ─────────────────────────────────────────────
    ("安全", "ānquán", "an toàn", "注意安全！", "Chú ý an toàn nhé!"),
    ("危险", "wēixiǎn", "nguy hiểm", "这里很危险。", "Nơi này rất nguy hiểm."),
    ("方便", "fāngbiàn", "tiện lợi / thuận tiện", "住在这里很方便。", "Sống ở đây rất tiện lợi."),
    ("麻烦", "máfan", "phiền phức / rắc rối", "不好意思，麻烦你了。", "Xin lỗi đã làm phiền bạn."),
    ("成功", "chénggōng", "thành công", "祝你成功！", "Chúc bạn thành công!"),
    ("失败", "shībài", "thất bại", "失败是成功之母。", "Thất bại là mẹ của thành công."),
    ("机会", "jīhuì", "cơ hội", "要抓住这个机会。", "Phải nắm lấy cơ hội này."),
    ("梦想", "mèngxiǎng", "ước mơ / giấc mơ", "我的梦想是环游世界。", "Ước mơ của tôi là đi vòng quanh thế giới."),
    ("希望", "xīwàng", "hy vọng / mong muốn", "我希望你快点好起来。", "Tôi hy vọng bạn sớm khỏe lại."),
    ("决定", "juédìng", "quyết định", "我决定去学汉语。", "Tôi quyết định học tiếng Trung."),
    ("改变", "gǎibiàn", "thay đổi", "我想改变自己。", "Tôi muốn thay đổi bản thân."),
    ("计划", "jìhuà", "kế hoạch", "你有什么计划？", "Bạn có kế hoạch gì không?"),
    ("准备", "zhǔnbèi", "chuẩn bị", "我已经准备好了。", "Tôi đã chuẩn bị xong rồi."),
    ("开始", "kāishǐ", "bắt đầu", "让我们开始吧！", "Hãy bắt đầu nào!"),
    ("结束", "jiéshù", "kết thúc / chấm dứt", "电影结束了。", "Bộ phim kết thúc rồi."),
    ("继续", "jìxù", "tiếp tục", "继续努力！", "Tiếp tục cố gắng!"),
    ("停止", "tíngzhǐ", "dừng lại / ngừng", "请停止说话。", "Xin hãy ngừng nói chuyện."),
    ("尝试", "chángshì", "thử / cố thử", "试试看，不要怕失败。", "Thử xem, đừng sợ thất bại."),
    ("比较", "bǐjiào", "so sánh / tương đối", "这个比较便宜。", "Cái này tương đối rẻ hơn."),
    ("选择", "xuǎnzé", "lựa chọn", "你有很多选择。", "Bạn có nhiều lựa chọn."),
    ("记得", "jìde", "nhớ / còn nhớ", "你记得我吗？", "Bạn còn nhớ tôi không?"),
    ("忘记", "wàngjì", "quên", "我忘记带钥匙了。", "Tôi quên mang chìa khóa."),
    ("理解", "lǐjiě", "hiểu / thông cảm", "我能理解你的感受。", "Tôi có thể hiểu cảm giác của bạn."),
    ("相信", "xiāngxìn", "tin tưởng / tin", "我相信你能做到。", "Tôi tin bạn có thể làm được."),
    ("感谢", "gǎnxiè", "cảm ơn / biết ơn", "非常感谢你的帮助！", "Cảm ơn rất nhiều vì sự giúp đỡ của bạn!"),
    ("分享", "fēnxiǎng", "chia sẻ", "我想跟你分享这个好消息。", "Tôi muốn chia sẻ tin vui này với bạn."),
    ("保护", "bǎohù", "bảo vệ", "要保护环境。", "Phải bảo vệ môi trường."),
    ("环境", "huánjìng", "môi trường", "保护环境从我做起。", "Bảo vệ môi trường bắt đầu từ chính mình."),
    ("节约", "jiéyuē", "tiết kiệm", "要节约用水。", "Phải tiết kiệm nước."),
    ("消息", "xiāoxi", "tin tức / thông tin", "你听到这个消息了吗？", "Bạn nghe tin này chưa?"),
    ("新闻", "xīnwén", "tin tức (báo chí)", "我每天看新闻。", "Tôi xem tin tức mỗi ngày."),
    ("世界", "shìjiè", "thế giới", "世界很大。", "Thế giới rất rộng lớn."),
    ("生活", "shēnghuó", "cuộc sống / sinh hoạt", "生活要积极向上。", "Cuộc sống phải tích cực hướng thượng."),
    ("幸福", "xìngfú", "hạnh phúc", "幸福就是家人在一起。", "Hạnh phúc là khi gia đình bên nhau."),
]
